- name: Install java 8.0
  become: true
  ansible.builtin.package:
    name: dotnet-sdk-8.0
  when: >-
    (
    ansible_distribution == "Ubuntu" and ansible_distribution_version is version('24.10', '<')
    ) or (
    ansible_distribution == "Fedora" and ansible_distribution_version is version('40', '<')
    )

- name: Install java 9.0
  become: true
  ansible.builtin.package:
    name: dotnet-sdk-9.0
  when: >-
    (
    ansible_distribution == "Ubuntu" and ansible_distribution_version is version('24.10', '>=')
    ) or (
    ansible_distribution == "Fedora" and ansible_distribution_version is version('40', '>=')
    )
