local M = {}
local manifest = require("custom.plugins.manifest")

M.commit = manifest["williamboman/mason.nvim"].commit

M.override_options = {
  ensure_installed = {
    "actionlint",
    "alex",
    "ansible-language-server",
    "ansible-lint",
    "arduino-language-server",
    "autopep8",
    "awk-language-server",
    "bash-language-server",
    "beautysh",
    "black",
    "clang-format",
    "clangd",
    "cmake-language-server",
    "cmakelang",
    "css-lsp",
    "dockerfile-language-server",
    "dot-language-server",
    "editorconfig-checker",
    "eslint_d",
    "flake8",
    "gitlint",
    "groovy-language-server",
    "hadolint",
    "html-lsp",
    "isort",
    "jedi-language-server",
    "jq",
    "json-lsp",
    "latexindent",
    "lua-language-server",
    "markdownlint",
    "mypy",
    "ocamlformat",
    "opencl-language-server",
    "perlnavigator",
    "puppet-editor-services",
    "pylint",
    "python-lsp-server",
    "rubocop",
    "ruby-lsp",
    "rust-analyzer",
    "rustfmt",
    "salt-lsp",
    "shellcheck",
    "shfmt",
    "sqlls",
    "stylua",
    "texlab",
    "vim-language-server",
    "write-good",
    "yaml-language-server",
    "yamlfmt",
    "yamllint",
    -- "asm-lsp", -- not working
    -- "powershell-editor-services", -- not working
  },
}

return M
