- name: Create zig directory
  ansible.builtin.file:
    path: "{{ home }}/.local/zig"
    state: directory
    mode: "0o755"

- name: Install zig
  ansible.builtin.unarchive:
    src: "{{ manifest.zig.url }}"
    dest: "{{ home }}/.local/zig"
    remote_src: true
    extra_opts:
      - --strip-components=1
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  retries: "{{ web_retries }}"
  delay: "{{ web_delay }}"
  register: zig_downloaded
  until: zig_downloaded is not failed

- name: Install zls
  ansible.builtin.unarchive:
    src: "{{ manifest.zls.url }}"
    dest: "{{ home }}/.local/bin"
    remote_src: true
    extra_opts:
      - --exclude=LICENSE
      - --exclude=*.md
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  retries: "{{ web_retries }}"
  delay: "{{ web_delay }}"
  register: zig_downloaded
  until: zig_downloaded is not failed

- name: Set up bash
  ansible.builtin.lineinfile:
    path: "{{ home }}/.bashrc"
    regexp: "source .*/{{ role_name }}/files"
    line: source {{ role_host_path }}/files/bash.sh

- name: Create symlink to fish config of {{ role_name }}
  ansible.builtin.file:
    src: "{{ role_host_path }}/files/{{ role_name }}.fish"
    dest: "{{ home }}/.config/fish/conf.d/{{ role_name }}.fish"
    state: link
