- name: Install rust completions
  ansible.builtin.shell: |
    rustup completions bash > {{ home }}/.local/share/bash-completion/completions/rustup
    rustup completions fish > {{ home }}/.config/fish/completions/rustup.fish
  args:
    executable: bash
  changed_when: false
