- name: Download rust installer
  ansible.builtin.get_url:
    url: https://sh.rustup.rs
    dest: "{{ dotfiles_tmp }}/sh.rustup.rs"
    mode: 0755
    force: true
  retries: "{{ web_retries }}"
  delay: "{{ web_delay }}"
  register: downloaded
  until: downloaded is not failed

- name: Install rust
  ansible.builtin.shell: |
    if ! command -v cargo &> /dev/null; then
      {{ dotfiles_tmp }}/sh.rustup.rs -y
      {{ home }}/.cargo/bin/rustup update
    fi
  args:
    executable: bash
  register: rust_update_status
  changed_when: ("unchanged" not in rust_update_status.stdout and rust_update_status.stdout != "")

- name: Install rust completions
  ansible.builtin.shell: |
    {{ home }}/.cargo/bin/rustup completions bash > {{ home }}/.local/share/bash-completion/completions/rustup
    {{ home }}/.cargo/bin/rustup completions fish > {{ home }}/.config/fish/completions/rustup.fish
  args:
    executable: bash
  changed_when: false

- name: Create symlink to {{ role_name }}.fish
  ansible.builtin.file:
    src: "{{ remote_role_path }}/files/{{ role_name }}.fish"
    dest: "{{ home }}/.config/fish/conf.d/{{ role_name }}.fish"
    state: link
