- name: credentials | Load local secrets vars
  ansible.builtin.include_vars:
    file: "{{ playbook_dir }}/roles/secrets/vars/local.yaml"

- name: credentials | Check if inside container
  ansible.builtin.shell: ([[ -f /.dockerenv || -f /run/.containerenv ]]) && echo true || echo false
  args:
    executable: bash
  changed_when: false
  register: secrets_container_out

- name: credentials | Set in_container status
  ansible.builtin.set_fact:
    in_container: "{{ secrets_container_out.stdout }}"

- name: credentials | Check if credentials are decrypted locally
  delegate_to: localhost
  ansible.builtin.stat:
    path: "{{ secrets_credentials_local_path }}"
  register: secrets_creds_status

- name: credentials | Set credentials
  ansible.builtin.set_fact:
    secrets_hashed_pass: "{{ secrets_creds.password | password_hash(salt=secrets_creds.salt) }}"
    secrets_pass: "{{ secrets_creds.password }}"
  vars:
    secrets_creds: "{{ lookup('ansible.builtin.file', secrets_credentials_local_path) | from_json }}"
  no_log: true
  # Do not set credentials in containers
  # See https://github.com/ansible/ansible/issues/80254
  when: secrets_creds_status.stat.exists and not in_container

- name: credentials | Set default credentials
  ansible.builtin.set_fact:
    secrets_hashed_pass: ""
    secrets_pass: ""
  when: not secrets_creds_status.stat.exists or in_container

- name: credentials | Set password for {{ secrets_user }}
  become: true
  ansible.builtin.user:
    name: "{{ secrets_user }}"
    password: "{{ secrets_hashed_pass }}"

- name: credentials | Set ansible_sudo_pass
  ansible.builtin.set_fact:
    ansible_sudo_pass: "{{ secrets_pass }}"
  no_log: true
