- name: Check if gpg key is installed
  ansible.builtin.shell: |
    set -o pipefail
    gpg --list-secret-keys | grep {{ gpg_email }} --quiet && echo "secret key imported" || true
  args:
    executable: bash
  register: gpg_imported
  changed_when: false

- name: Import gpg key
  block:
    - name: Copy gpg key
      ansible.builtin.copy:
        src: "{{ gpg_key }}"
        dest: "{{ dotfiles_tmp }}/private.gpg"
        mode: 0600

    - name: Import gpg key
      ansible.builtin.shell: |
        gpg --import "{{ dotfiles_tmp }}/private.gpg" 2>&1
      args:
        executable: bash
      register: gpg_imported_now
      changed_when: >
        ("secret key imported" in gpg_imported_now.stdout) and ("secret keys unchanged" not in gpg_imported_now.stdout)
  when: ("secret key imported" not in gpg_imported.stdout) and (gpg_key != "")

- name: Decrypt git secrets
  ansible.builtin.shell: |
    git secret reveal -f
  args:
    chdir: "{{ dotfiles_path }}"
  when: ("secret key imported" in gpg_imported.stdout) or (gpg_imported_now is not skipped)
  changed_when: false
  tags:
    - skip_ansible_lint
