- name: Install luarocks completions
  ansible.builtin.shell: |
    luarocks completion bash > {{ home }}/.local/share/bash-completion/completions/luarocks
    luarocks completion fish > {{ home }}/.config/fish/completions/luarocks.fish
  args:
    executable: bash
  changed_when: false

- name: Create lua.fish config
  ansible.builtin.template:
    src: lua.fish
    dest: "{{ home }}/.config/fish/conf.d/lua.fish"
    mode: "0o644"

- name: Install json4Lua
  become: true
  ansible.builtin.shell: |
    set -o pipefail
    if ! luarocks list json4Lua | grep --quiet "(installed)"; then
      luarocks install --server=http://rocks.moonscript.org/manifests/amrhassan json4Lua
    fi
  args:
    executable: bash
  register: lua_installed
  changed_when: lua_installed.stdout != ""

- name: Create ~/.config/luacheck directory
  ansible.builtin.file:
    path: "{{ home }}/.config/luacheck"
    state: directory
    mode: "0o755"

# https://luacheck.readthedocs.io/en/stable/config.html#configuration-file
- name: Create symlink to global luacheck config
  ansible.builtin.file:
    src: "{{ role_host_path }}/files/luacheckrc"
    dest: "{{ home }}/.config/luacheck/.luacheckrc"
    state: link
