- name: Add fish gpg key
  become: true
  ansible.builtin.get_url:
    url: "{{ shell_fish_key_url }}"
    dest: "{{ apt_keys }}/fish.asc"
    mode: "0o644"
    checksum: "{{ shell_fish_key_checksum }}"
  register: shell_fish_key_downloaded
  retries: "{{ web_retries }}"
  delay: "{{ web_delay }}"
  until: shell_fish_key_downloaded is not failed

- name: Add fish repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by={{ apt_keys }}/fish.asc] {{ shell_fish_repo }}
      {{ ansible_distribution_release }} main

- name: Add fish src repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb-src [arch=amd64 signed-by={{ apt_keys }}/fish.asc] {{ shell_fish_repo }}
      {{ ansible_distribution_release }} main

- name: Install fish
  become: true
  ansible.builtin.apt:
    name: fish

- name: Create fish functions directory
  ansible.builtin.file:
    path: "{{ home }}/.config/fish/functions"
    state: directory
    mode: "0o755"

- name: Create fish conf.d directory
  ansible.builtin.file:
    path: "{{ home }}/.config/fish/conf.d"
    state: directory
    mode: "0o755"

- name: Create fish completions directory
  ansible.builtin.file:
    path: "{{ home }}/.config/fish/completions"
    state: directory
    mode: "0o755"

- name: Create symlink to fish config of {{ role_name }}
  ansible.builtin.file:
    src: "{{ remote_role_path }}/files/{{ role_name }}.fish"
    dest: "{{ home }}/.config/fish/conf.d/{{ role_name }}.fish"
    state: link

- name: Change user shell to fish
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    shell: /usr/bin/fish

- name: Install bash-completion
  become: true
  ansible.builtin.apt:
    name: bash-completion

- name: Create bash completions directory
  ansible.builtin.file:
    path: "{{ home }}/.local/share/bash-completion/completions"
    state: directory
    mode: "0o755"

- name: Set up bash
  ansible.builtin.lineinfile:
    path: "{{ home }}/.bashrc"
    regexp: "source .*/{{ role_name }}/files"
    line: source {{ remote_role_path }}/files/bash.sh
    create: true
    mode: "0o644"

- name: Create symlinks to fish functions
  ansible.builtin.file:
    src: "{{ remote_role_path }}/files/fish_functions/{{ item | basename }}"
    dest: "{{ home }}/.config/fish/functions/{{ item | basename }}"
    state: link
  loop: "{{ lookup('fileglob', '{{ role_path }}/files/fish_functions/*', wantlist=True) }}"

- name: Create ~/.local/bin directory
  ansible.builtin.file:
    path: "{{ home }}/.local/bin"
    state: directory
    mode: "0o755"
