- name: Create ~/.local/bin directory
  ansible.builtin.file:
    path: "{{ home }}/.local/bin"
    state: directory
    mode: "0o755"

- name: Create ~/.local/share directory
  ansible.builtin.file:
    path: "{{ home }}/.local/share"
    state: directory
    mode: "0o755"

- name: Download fish
  ansible.builtin.unarchive:
    src: "{{ manifest.fish.url }}"
    dest: "{{ home }}/.local/bin"
    remote_src: true
    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/unarchive_module.html
    # If left unspecified and we are configuring for root user,
    # ansible will not set user and group for us,
    # which leads to incorrect ownership of the extracted files
    # and idempotency issues.
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  retries: "{{ web_retries }}"
  delay: "{{ web_delay }}"
  register: shell_utils_downloaded
  until: shell_utils_downloaded is not failed

- name: Install fish configs
  ansible.builtin.shell: |
    set -o pipefail
    echo yes | ~/.local/bin/fish --install
  args:
    executable: bash
    creates: "{{ home }}/.local/share/fish/install"

- name: Create fish functions directory
  ansible.builtin.file:
    path: "{{ home }}/.config/fish/functions"
    state: directory
    mode: "0o755"

- name: Create fish conf.d directory
  ansible.builtin.file:
    path: "{{ home }}/.config/fish/conf.d"
    state: directory
    mode: "0o755"

- name: Create fish completions directory
  ansible.builtin.file:
    path: "{{ home }}/.config/fish/completions"
    state: directory
    mode: "0o755"

- name: Create symlink to fish config of {{ role_name }}
  ansible.builtin.file:
    src: "{{ role_host_path }}/files/{{ role_name }}.fish"
    dest: "{{ home }}/.config/fish/conf.d/{{ role_name }}.fish"
    state: link

- name: Change user shell to fish
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    shell: "{{ home }}/.local/bin/fish"

- name: Install bash-completion
  become: true
  ansible.builtin.package:
    name: bash-completion

- name: Create bash completions directory
  ansible.builtin.file:
    path: "{{ home }}/.local/share/bash-completion/completions"
    state: directory
    mode: "0o755"

- name: Set up bash
  ansible.builtin.lineinfile:
    path: "{{ home }}/.bashrc"
    regexp: "source .*/{{ role_name }}/files"
    line: source {{ role_host_path }}/files/bash.sh
    create: true
    mode: "0o644"

- name: Create symlinks to fish functions
  ansible.builtin.file:
    src: "{{ role_host_path }}/files/fish_functions/{{ item | basename }}"
    dest: "{{ home }}/.config/fish/functions/{{ item | basename }}"
    state: link
  loop: "{{ lookup('fileglob', '{{ role_path }}/files/fish_functions/*', wantlist=True) }}"
