- name: Create fish functions directory
  ansible.builtin.file:
    path: "{{ home }}/.config/fish/functions"
    state: directory
    mode: "0o755"

- name: Create fish conf.d directory
  ansible.builtin.file:
    path: "{{ home }}/.config/fish/conf.d"
    state: directory
    mode: "0o755"

- name: Create fish completions directory
  ansible.builtin.file:
    path: "{{ home }}/.config/fish/completions"
    state: directory
    mode: "0o755"

- name: Create symlink to fish config of {{ role_name }}
  ansible.builtin.file:
    src: "{{ role_host_path }}/files/{{ role_name }}.fish"
    dest: "{{ home }}/.config/fish/conf.d/{{ role_name }}.fish"
    state: link

- name: Create nu autoload directory
  ansible.builtin.file:
    path: "{{ home }}/.config/nushell/autoload"
    state: directory
    mode: "0o755"

- name: Create symlink to nu config
  ansible.builtin.file:
    src: "{{ role_host_path }}/files/config.nu"
    dest: "{{ home }}/.config/nushell/config.nu"
    state: link

- name: Install bash-completion
  become: true
  ansible.builtin.package:
    name: bash-completion

- name: Create bash completions directory
  ansible.builtin.file:
    path: "{{ home }}/.local/share/bash-completion/completions"
    state: directory
    mode: "0o755"

- name: Set up bash
  ansible.builtin.lineinfile:
    path: "{{ home }}/.bashrc"
    regexp: "source .*/{{ role_name }}/files"
    line: source {{ role_host_path }}/files/bash.sh
    create: true
    mode: "0o644"

- name: Create symlinks to fish functions
  ansible.builtin.file:
    src: "{{ role_host_path }}/files/fish_functions/{{ item | basename }}"
    dest: "{{ home }}/.config/fish/functions/{{ item | basename }}"
    state: link
  loop: "{{ lookup('fileglob', '{{ role_path }}/files/fish_functions/*', wantlist=True) }}"
