# GNOME dconf settings. The `_dconf/settings.nix` module is generated by
# `dotfiles gui` from the current dconf state filtered through `_dconf/rules.yaml`.
{ flake.modules.homeManager.base = ./_dconf/settings.nix; }
