chrome_deb: https://dl.google.com/linux/direct/google-chrome-stable_current_{{ deb_arch }}.deb
chrome_rpm: https://dl.google.com/linux/direct/google-chrome-stable_current_{{ ansible_architecture }}.rpm
