- name: Install sudo
  become: true
  ansible.builtin.package:
    name: sudo

- name: Set correct credentials for the user {{ user }}
  ansible.builtin.include_tasks:
    file: "roles/secrets/tasks/credentials.yaml"

- name: Append admin groups for user "{{ user }}"
  become: true
  ansible.builtin.user:
    name: "{{ user }}"
    groups:
      - adm
      - sudo
    append: true

- name: Add authorized_key for {{ user }}
  become: true
  ansible.posix.authorized_key:
    user: "{{ user }}"
    key: "{{ lookup('file', '{{ secrets_ssh_local_path }}/id_rsa.pub') }}"
  when: ansible_connection == "ssh"

- name: Switch ansible_user
  ansible.builtin.set_fact:
    ansible_user: "{{ user }}"
  tags:
    # TODO: see https://github.com/ansible/ansible-lint/issues/3456
    - skip_ansible_lint
