- name: Create test linux container
  hosts: localhost
  tasks:
    - name: Spin up {{ container }}
      containers.podman.podman_container:
        name: "{{ container }}"
        image: "{{ image }}"
        interactive: true
        privileged: true
        tty: true
        # Mount project in some neutral folder
        # This allows two different scenarios:
        # 1. Test configuration through podman connection, imitating remote machine config
        # 2. Test configuration directly inside container as a local machine, which is much faster
        #    Note, that we need specifically a mount, not a copy, because in case of local debugging we
        #    need to introduce lots of changes. Copying the project each time would be too tedious.
        volume: "{{ playbook_dir }}:/dotfiles_debug"
