- name: Create test linux container
  hosts: localhost
  tasks:
    - name: Spin up {{ container }}
      containers.podman.podman_container:
        name: "{{ container }}"
        image: "{{ image }}"
        interactive: true
        privileged: true
        tty: true
