- name: Create test linux container
  hosts: localhost
  tasks:
    - name: Spin up dotfiles_{{ ubuntu_tag }}
      containers.podman.podman_container:
        name: dotfiles_{{ ubuntu_tag }}
        image: ubuntu:{{ ubuntu_tag }}
        interactive: true
        privileged: true
        tty: true
