apt_keys: /etc/apt/trusted.gpg.d # noqa: var-naming[no-role-prefix]
ubuntu_keyserver: https://keyserver.ubuntu.com/pks/lookup?op=get&search= # noqa: var-naming[no-role-prefix]
deb_arch: "{{ {'aarch64': 'arm64', 'x86_64': 'amd64'}[ansible_architecture] }}" # noqa: var-naming[no-role-prefix]
pack: "{{ {'Ubuntu': 'deb', 'Fedora': 'rpm'}[ansible_distribution] }}" # noqa: var-naming[no-role-prefix]
pack_arch: # noqa: var-naming[no-role-prefix]
  "{{ {'Ubuntu': deb_arch, 'Fedora': ansible_architecture}[ansible_distribution] }}"
