- name: Create projects directory
  ansible.builtin.file:
    path: "{{ dotfiles_parent_path }}"
    state: directory
    mode: "0o755"

- name: Copy dotfiles repository
  ansible.posix.synchronize:
    src: "{{ playbook_dir }}"
    dest: "{{ dotfiles_parent_path }}"
    rsync_opts: "--filter=':- .gitignore'"
    owner: false
    group: false
  register: dotfiles_changed
  changed_when: dotfiles_changed.stdout_lines | length >= 10

- name: Show changed files
  ansible.builtin.debug:
    msg:
      - "Total changed files: {{ dotfiles_changed.stdout_lines | length }}"
      - "First 10 changed files:"
      - "{{ dotfiles_changed.stdout_lines[0:10] }}"

- name: Create tmp dir in dotfiles repo
  ansible.builtin.file:
    path: "{{ dotfiles_tmp }}"
    state: directory
    mode: "0o755"
