- name: cmake | Download installation script
  ansible.builtin.get_url:
    url: "{{ manifest.cmake.url }}"
    dest: "{{ dotfiles_tmp }}/cmake.sh"
    mode: "0o755"
    force: true
  retries: "{{ web_retries }}"
  delay: "{{ web_delay }}"
  register: cpp_downloaded
  until: cpp_downloaded is not failed

- name: cmake | Install cmake
  become: true
  ansible.builtin.shell: |
    set -o pipefail
    current_version=$(cmake --version 2>&1 | grep --perl-regexp --only-matching "\d+\.\d+\.\d+" || true)
    cmake_version=$(echo {{ manifest.cmake.url }} | grep --perl-regexp --only-matching "download/v\K\d+\.\d+\.\d+")
    if [[ "$cmake_version" != "$current_version" ]]; then
      "{{ dotfiles_tmp }}/cmake.sh" --skip-license --exclude-subdir --prefix=/usr/local
      echo false
    else
      echo true
    fi
  args:
    executable: bash
  changed_when: cpp_cmake_matches.stdout != "true"
  register: cpp_cmake_matches
