- name: Add ppa:ubuntu-toolchain-r/test repository
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:ubuntu-toolchain-r/test

- name: Install GCC
  become: true
  ansible.builtin.apt:
    name:
      - gcc-{{ gcc_version }}
      - g++-{{ gcc_version }}

- name: Update GCC alternatives
  become: true
  community.general.alternatives:
    name: gcc
    link: /usr/bin/gcc
    path: /usr/bin/gcc-{{ gcc_version }}
    priority: "{{ gcc_version }}0"
    subcommands:
      - name: g++
        link: /usr/bin/g++
        path: /usr/bin/g++-{{ gcc_version }}
      - name: gcc-ar
        link: /usr/bin/gcc-ar
        path: /usr/bin/gcc-ar-{{ gcc_version }}
      - name: gcc-nm
        link: /usr/bin/gcc-nm
        path: /usr/bin/gcc-nm-{{ gcc_version }}
      - name: gcc-ranlib
        link: /usr/bin/gcc-ranlib
        path: /usr/bin/gcc-ranlib-{{ gcc_version }}
      - name: gcov
        link: /usr/bin/gcov
        path: /usr/bin/gcov-{{ gcc_version }}
      - name: gcov-dump
        link: /usr/bin/gcov-dump
        path: /usr/bin/gcov-dump-{{ gcc_version }}
      - name: gcov-tool
        link: /usr/bin/gcov-tool
        path: /usr/bin/gcov-tool-{{ gcc_version }}
      - name: lto-dump
        link: /usr/bin/lto-dump
        path: /usr/bin/lto-dump-{{ gcc_version }}

- name: Update cc alternative
  become: true
  community.general.alternatives:
    name: cc
    link: /usr/bin/cc
    path: /usr/bin/gcc-{{ gcc_version }}
    priority: "{{ gcc_version }}0"

- name: Fix cyclic cpp symlinks
  become: true
  ansible.builtin.shell: |
    set -o pipefail
    if [[ "$(readlink /etc/alternatives/cpp)" == "/usr/bin/cpp" ]]; then
      rm /etc/alternatives/cpp
      echo changed
    fi
  args:
    executable: bash
  register: output
  changed_when: '"changed" in output.stdout'

- name: Update cpp alternative
  become: true
  community.general.alternatives:
    name: cpp
    link: /usr/bin/cpp
    path: /usr/bin/cpp-{{ gcc_version }}
    priority: "{{ gcc_version }}0"
