- name: Add toolchain-r gpg key
  become: true
  ansible.builtin.get_url:
    url: "{{ cpp_toolchain_r_key_url }}"
    dest: /etc/apt/trusted.gpg.d/toolchain-r.asc
    mode: "0o644"

- name: Remove default toolchain-r repository
  become: true
  ansible.builtin.file:
    dest: "{{ cpp_toolchain_r_default_path }}"
    state: absent

- name: Add toolchain-r repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/toolchain-r.asc] {{ cpp_toolchain_r_repo }}
      {{ ansible_distribution_release }} main

- name: Add toolchain-r src repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb-src [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/toolchain-r.asc] {{ cpp_toolchain_r_repo }}
      {{ ansible_distribution_release }} main

- name: Install GCC
  become: true
  ansible.builtin.apt:
    name:
      - gcc-{{ cpp_gcc_version }}
      - g++-{{ cpp_gcc_version }}

- name: Update GCC alternatives
  become: true
  community.general.alternatives:
    name: gcc
    link: /usr/bin/gcc
    path: /usr/bin/gcc-{{ cpp_gcc_version }}
    priority: "{{ cpp_gcc_version }}0"
    subcommands:
      - name: g++
        link: /usr/bin/g++
        path: /usr/bin/g++-{{ cpp_gcc_version }}
      - name: gcc-ar
        link: /usr/bin/gcc-ar
        path: /usr/bin/gcc-ar-{{ cpp_gcc_version }}
      - name: gcc-nm
        link: /usr/bin/gcc-nm
        path: /usr/bin/gcc-nm-{{ cpp_gcc_version }}
      - name: gcc-ranlib
        link: /usr/bin/gcc-ranlib
        path: /usr/bin/gcc-ranlib-{{ cpp_gcc_version }}
      - name: gcov
        link: /usr/bin/gcov
        path: /usr/bin/gcov-{{ cpp_gcc_version }}
      - name: gcov-dump
        link: /usr/bin/gcov-dump
        path: /usr/bin/gcov-dump-{{ cpp_gcc_version }}
      - name: gcov-tool
        link: /usr/bin/gcov-tool
        path: /usr/bin/gcov-tool-{{ cpp_gcc_version }}
      - name: lto-dump
        link: /usr/bin/lto-dump
        path: /usr/bin/lto-dump-{{ cpp_gcc_version }}

- name: Update cc alternative
  become: true
  community.general.alternatives:
    name: cc
    link: /usr/bin/cc
    path: /usr/bin/gcc-{{ cpp_gcc_version }}
    priority: "{{ cpp_gcc_version }}0"

- name: Fix cyclic cpp symlinks
  become: true
  ansible.builtin.shell: |
    set -o pipefail
    if [[ "$(readlink /etc/alternatives/cpp)" == "/usr/bin/cpp" ]]; then
      rm /etc/alternatives/cpp
      echo changed
    fi
  args:
    executable: bash
  register: cpp_output
  changed_when: '"changed" in cpp_output.stdout'

- name: Update cpp alternative
  become: true
  community.general.alternatives:
    name: cpp
    link: /usr/bin/cpp
    path: /usr/bin/cpp-{{ cpp_gcc_version }}
    priority: "{{ cpp_gcc_version }}0"
