- name: Add LLVM gpg key
  become: true
  ansible.builtin.get_url:
    url: "{{ cpp_llvm_gpg }}"
    dest: "{{ apt_keys }}/llvm.asc"
    mode: "0o644"

- name: Add LLVM repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by={{ apt_keys }}/llvm.asc] {{ cpp_llvm_repo }} llvm-toolchain-{{
      ansible_distribution_release }}-{{ cpp_llvm_version }} main

- name: Install LLVM
  become: true
  ansible.builtin.apt:
    name:
      - clang-format-{{ cpp_llvm_version }}
      - clang-tidy-{{ cpp_llvm_version }}
      - clang-tools-{{ cpp_llvm_version }}
      - clang-{{ cpp_llvm_version }}
      - clangd-{{ cpp_llvm_version }}
      - libc++-{{ cpp_llvm_version }}-dev
      - libc++abi-{{ cpp_llvm_version }}-dev
      - libclang-common-{{ cpp_llvm_version }}-dev
      - libclang-cpp{{ cpp_llvm_version }}-dev
      - libclang-{{ cpp_llvm_version }}-dev
      - libomp-{{ cpp_llvm_version }}-dev
      - libunwind-{{ cpp_llvm_version }}-dev
      - lld-{{ cpp_llvm_version }}
      - lld-{{ cpp_llvm_version }}
      - lldb-{{ cpp_llvm_version }}
      - lldb-{{ cpp_llvm_version }}
      - llvm-{{ cpp_llvm_version }}-dev
      - llvm-{{ cpp_llvm_version }}-tools

- name: Update LLVM alternatives
  become: true
  community.general.alternatives:
    name: clang
    link: /usr/bin/clang
    path: /usr/bin/clang-{{ cpp_llvm_version }}
    priority: "{{ cpp_llvm_version }}0"
    subcommands:
      - name: FileCheck
        link: /usr/bin/FileCheck
        path: /usr/bin/FileCheck-{{ cpp_llvm_version }}
      - name: analyze-build
        link: /usr/bin/analyze-build
        path: /usr/bin/analyze-build-{{ cpp_llvm_version }}
      - name: asan_symbolize
        link: /usr/bin/asan_symbolize
        path: /usr/bin/asan_symbolize-{{ cpp_llvm_version }}
      - name: bugpoint
        link: /usr/bin/bugpoint
        path: /usr/bin/bugpoint-{{ cpp_llvm_version }}
      - name: c-index-test
        link: /usr/bin/c-index-test
        path: /usr/bin/c-index-test-{{ cpp_llvm_version }}
      - name: clang-apply-replacements
        link: /usr/bin/clang-apply-replacements
        path: /usr/bin/clang-apply-replacements-{{ cpp_llvm_version }}
      - name: clang-change-namespace
        link: /usr/bin/clang-change-namespace
        path: /usr/bin/clang-change-namespace-{{ cpp_llvm_version }}
      - name: clang-check
        link: /usr/bin/clang-check
        path: /usr/bin/clang-check-{{ cpp_llvm_version }}
      - name: clang-cl
        link: /usr/bin/clang-cl
        path: /usr/bin/clang-cl-{{ cpp_llvm_version }}
      - name: clang-cpp
        link: /usr/bin/clang-cpp
        path: /usr/bin/clang-cpp-{{ cpp_llvm_version }}
      - name: clang-doc
        link: /usr/bin/clang-doc
        path: /usr/bin/clang-doc-{{ cpp_llvm_version }}
      - name: clang-extdef-mapping
        link: /usr/bin/clang-extdef-mapping
        path: /usr/bin/clang-extdef-mapping-{{ cpp_llvm_version }}
      - name: clang-include-fixer
        link: /usr/bin/clang-include-fixer
        path: /usr/bin/clang-include-fixer-{{ cpp_llvm_version }}
      - name: clang-linker-wrapper
        link: /usr/bin/clang-linker-wrapper
        path: /usr/bin/clang-linker-wrapper-{{ cpp_llvm_version }}
      - name: clang-move
        link: /usr/bin/clang-move
        path: /usr/bin/clang-move-{{ cpp_llvm_version }}
      - name: clang-nvlink-wrapper
        link: /usr/bin/clang-nvlink-wrapper
        path: /usr/bin/clang-nvlink-wrapper-{{ cpp_llvm_version }}
      - name: clang-offload-bundler
        link: /usr/bin/clang-offload-bundler
        path: /usr/bin/clang-offload-bundler-{{ cpp_llvm_version }}
      - name: clang-offload-wrapper
        link: /usr/bin/clang-offload-wrapper
        path: /usr/bin/clang-offload-wrapper-{{ cpp_llvm_version }}
      - name: clang-query
        link: /usr/bin/clang-query
        path: /usr/bin/clang-query-{{ cpp_llvm_version }}
      - name: clang-refactor
        link: /usr/bin/clang-refactor
        path: /usr/bin/clang-refactor-{{ cpp_llvm_version }}
      - name: clang-rename
        link: /usr/bin/clang-rename
        path: /usr/bin/clang-rename-{{ cpp_llvm_version }}
      - name: clang-reorder-fields
        link: /usr/bin/clang-reorder-fields
        path: /usr/bin/clang-reorder-fields-{{ cpp_llvm_version }}
      - name: clang-repl
        link: /usr/bin/clang-repl
        path: /usr/bin/clang-repl-{{ cpp_llvm_version }}
      - name: clang-scan-deps
        link: /usr/bin/clang-scan-deps
        path: /usr/bin/clang-scan-deps-{{ cpp_llvm_version }}
      - name: clangd
        link: /usr/bin/clangd
        path: /usr/bin/clangd-{{ cpp_llvm_version }}
      - name: count
        link: /usr/bin/count
        path: /usr/bin/count-{{ cpp_llvm_version }}
      - name: diagtool
        link: /usr/bin/diagtool
        path: /usr/bin/diagtool-{{ cpp_llvm_version }}
      - name: dsymutil
        link: /usr/bin/dsymutil
        path: /usr/bin/dsymutil-{{ cpp_llvm_version }}
      - name: find-all-symbols
        link: /usr/bin/find-all-symbols
        path: /usr/bin/find-all-symbols-{{ cpp_llvm_version }}
      - name: git-clang-format
        link: /usr/bin/git-clang-format
        path: /usr/bin/git-clang-format-{{ cpp_llvm_version }}
      - name: hmaptool
        link: /usr/bin/hmaptool
        path: /usr/bin/hmaptool-{{ cpp_llvm_version }}
      - name: hwasan_symbolize
        link: /usr/bin/hwasan_symbolize
        path: /usr/bin/hwasan_symbolize-{{ cpp_llvm_version }}
      - name: intercept-build
        link: /usr/bin/intercept-build
        path: /usr/bin/intercept-build-{{ cpp_llvm_version }}
      - name: ld.lld
        link: /usr/bin/ld.lld
        path: /usr/bin/ld.lld-{{ cpp_llvm_version }}
      - name: ld64.lld
        link: /usr/bin/ld64.lld
        path: /usr/bin/ld64.lld-{{ cpp_llvm_version }}
      - name: llc
        link: /usr/bin/llc
        path: /usr/bin/llc-{{ cpp_llvm_version }}
      - name: lld
        link: /usr/bin/lld
        path: /usr/bin/lld-{{ cpp_llvm_version }}
      - name: lld-link
        link: /usr/bin/lld-link
        path: /usr/bin/lld-link-{{ cpp_llvm_version }}
      - name: lldb
        link: /usr/bin/lldb
        path: /usr/bin/lldb-{{ cpp_llvm_version }}
      - name: lldb-argdumper
        link: /usr/bin/lldb-argdumper
        path: /usr/bin/lldb-argdumper-{{ cpp_llvm_version }}
      - name: lldb-instr
        link: /usr/bin/lldb-instr
        path: /usr/bin/lldb-instr-{{ cpp_llvm_version }}
      - name: lldb-server
        link: /usr/bin/lldb-server
        path: /usr/bin/lldb-server-{{ cpp_llvm_version }}
      - name: lldb-vscode
        link: /usr/bin/lldb-vscode
        path: /usr/bin/lldb-vscode-{{ cpp_llvm_version }}
      - name: lli
        link: /usr/bin/lli
        path: /usr/bin/lli-{{ cpp_llvm_version }}
      - name: lli-child-target
        link: /usr/bin/lli-child-target
        path: /usr/bin/lli-child-target-{{ cpp_llvm_version }}
      - name: llvm-PerfectShuffle
        link: /usr/bin/llvm-PerfectShuffle
        path: /usr/bin/llvm-PerfectShuffle-{{ cpp_llvm_version }}
      - name: llvm-addr2line
        link: /usr/bin/llvm-addr2line
        path: /usr/bin/llvm-addr2line-{{ cpp_llvm_version }}
      - name: llvm-ar
        link: /usr/bin/llvm-ar
        path: /usr/bin/llvm-ar-{{ cpp_llvm_version }}
      - name: llvm-as
        link: /usr/bin/llvm-as
        path: /usr/bin/llvm-as-{{ cpp_llvm_version }}
      - name: llvm-bcanalyzer
        link: /usr/bin/llvm-bcanalyzer
        path: /usr/bin/llvm-bcanalyzer-{{ cpp_llvm_version }}
      - name: llvm-bitcode-strip
        link: /usr/bin/llvm-bitcode-strip
        path: /usr/bin/llvm-bitcode-strip-{{ cpp_llvm_version }}
      - name: llvm-c-test
        link: /usr/bin/llvm-c-test
        path: /usr/bin/llvm-c-test-{{ cpp_llvm_version }}
      - name: llvm-cat
        link: /usr/bin/llvm-cat
        path: /usr/bin/llvm-cat-{{ cpp_llvm_version }}
      - name: llvm-cfi-verify
        link: /usr/bin/llvm-cfi-verify
        path: /usr/bin/llvm-cfi-verify-{{ cpp_llvm_version }}
      - name: llvm-config
        link: /usr/bin/llvm-config
        path: /usr/bin/llvm-config-{{ cpp_llvm_version }}
      - name: llvm-cov
        link: /usr/bin/llvm-cov
        path: /usr/bin/llvm-cov-{{ cpp_llvm_version }}
      - name: llvm-cvtres
        link: /usr/bin/llvm-cvtres
        path: /usr/bin/llvm-cvtres-{{ cpp_llvm_version }}
      - name: llvm-cxxdump
        link: /usr/bin/llvm-cxxdump
        path: /usr/bin/llvm-cxxdump-{{ cpp_llvm_version }}
      - name: llvm-cxxfilt
        link: /usr/bin/llvm-cxxfilt
        path: /usr/bin/llvm-cxxfilt-{{ cpp_llvm_version }}
      - name: llvm-cxxmap
        link: /usr/bin/llvm-cxxmap
        path: /usr/bin/llvm-cxxmap-{{ cpp_llvm_version }}
      - name: llvm-debuginfod-find
        link: /usr/bin/llvm-debuginfod-find
        path: /usr/bin/llvm-debuginfod-find-{{ cpp_llvm_version }}
      - name: llvm-diff
        link: /usr/bin/llvm-diff
        path: /usr/bin/llvm-diff-{{ cpp_llvm_version }}
      - name: llvm-dis
        link: /usr/bin/llvm-dis
        path: /usr/bin/llvm-dis-{{ cpp_llvm_version }}
      - name: llvm-dlltool
        link: /usr/bin/llvm-dlltool
        path: /usr/bin/llvm-dlltool-{{ cpp_llvm_version }}
      - name: llvm-dwarfdump
        link: /usr/bin/llvm-dwarfdump
        path: /usr/bin/llvm-dwarfdump-{{ cpp_llvm_version }}
      - name: llvm-dwp
        link: /usr/bin/llvm-dwp
        path: /usr/bin/llvm-dwp-{{ cpp_llvm_version }}
      - name: llvm-exegesis
        link: /usr/bin/llvm-exegesis
        path: /usr/bin/llvm-exegesis-{{ cpp_llvm_version }}
      - name: llvm-extract
        link: /usr/bin/llvm-extract
        path: /usr/bin/llvm-extract-{{ cpp_llvm_version }}
      - name: llvm-gsymutil
        link: /usr/bin/llvm-gsymutil
        path: /usr/bin/llvm-gsymutil-{{ cpp_llvm_version }}
      - name: llvm-ifs
        link: /usr/bin/llvm-ifs
        path: /usr/bin/llvm-ifs-{{ cpp_llvm_version }}
      - name: llvm-install-name-tool
        link: /usr/bin/llvm-install-name-tool
        path: /usr/bin/llvm-install-name-tool-{{ cpp_llvm_version }}
      - name: llvm-jitlink
        link: /usr/bin/llvm-jitlink
        path: /usr/bin/llvm-jitlink-{{ cpp_llvm_version }}
      - name: llvm-jitlink-executor
        link: /usr/bin/llvm-jitlink-executor
        path: /usr/bin/llvm-jitlink-executor-{{ cpp_llvm_version }}
      - name: llvm-lib
        link: /usr/bin/llvm-lib
        path: /usr/bin/llvm-lib-{{ cpp_llvm_version }}
      - name: llvm-libtool-darwin
        link: /usr/bin/llvm-libtool-darwin
        path: /usr/bin/llvm-libtool-darwin-{{ cpp_llvm_version }}
      - name: llvm-link
        link: /usr/bin/llvm-link
        path: /usr/bin/llvm-link-{{ cpp_llvm_version }}
      - name: llvm-lipo
        link: /usr/bin/llvm-lipo
        path: /usr/bin/llvm-lipo-{{ cpp_llvm_version }}
      - name: llvm-lto
        link: /usr/bin/llvm-lto
        path: /usr/bin/llvm-lto-{{ cpp_llvm_version }}
      - name: llvm-lto2
        link: /usr/bin/llvm-lto2
        path: /usr/bin/llvm-lto2-{{ cpp_llvm_version }}
      - name: llvm-mc
        link: /usr/bin/llvm-mc
        path: /usr/bin/llvm-mc-{{ cpp_llvm_version }}
      - name: llvm-mca
        link: /usr/bin/llvm-mca
        path: /usr/bin/llvm-mca-{{ cpp_llvm_version }}
      - name: llvm-ml
        link: /usr/bin/llvm-ml
        path: /usr/bin/llvm-ml-{{ cpp_llvm_version }}
      - name: llvm-modextract
        link: /usr/bin/llvm-modextract
        path: /usr/bin/llvm-modextract-{{ cpp_llvm_version }}
      - name: llvm-mt
        link: /usr/bin/llvm-mt
        path: /usr/bin/llvm-mt-{{ cpp_llvm_version }}
      - name: llvm-nm
        link: /usr/bin/llvm-nm
        path: /usr/bin/llvm-nm-{{ cpp_llvm_version }}
      - name: llvm-objcopy
        link: /usr/bin/llvm-objcopy
        path: /usr/bin/llvm-objcopy-{{ cpp_llvm_version }}
      - name: llvm-objdump
        link: /usr/bin/llvm-objdump
        path: /usr/bin/llvm-objdump-{{ cpp_llvm_version }}
      - name: llvm-opt-report
        link: /usr/bin/llvm-opt-report
        path: /usr/bin/llvm-opt-report-{{ cpp_llvm_version }}
      - name: llvm-otool
        link: /usr/bin/llvm-otool
        path: /usr/bin/llvm-otool-{{ cpp_llvm_version }}
      - name: llvm-pdbutil
        link: /usr/bin/llvm-pdbutil
        path: /usr/bin/llvm-pdbutil-{{ cpp_llvm_version }}
      - name: llvm-profdata
        link: /usr/bin/llvm-profdata
        path: /usr/bin/llvm-profdata-{{ cpp_llvm_version }}
      - name: llvm-profgen
        link: /usr/bin/llvm-profgen
        path: /usr/bin/llvm-profgen-{{ cpp_llvm_version }}
      - name: llvm-ranlib
        link: /usr/bin/llvm-ranlib
        path: /usr/bin/llvm-ranlib-{{ cpp_llvm_version }}
      - name: llvm-rc
        link: /usr/bin/llvm-rc
        path: /usr/bin/llvm-rc-{{ cpp_llvm_version }}
      - name: llvm-readelf
        link: /usr/bin/llvm-readelf
        path: /usr/bin/llvm-readelf-{{ cpp_llvm_version }}
      - name: llvm-readobj
        link: /usr/bin/llvm-readobj
        path: /usr/bin/llvm-readobj-{{ cpp_llvm_version }}
      - name: llvm-reduce
        link: /usr/bin/llvm-reduce
        path: /usr/bin/llvm-reduce-{{ cpp_llvm_version }}
      - name: llvm-rtdyld
        link: /usr/bin/llvm-rtdyld
        path: /usr/bin/llvm-rtdyld-{{ cpp_llvm_version }}
      - name: llvm-sim
        link: /usr/bin/llvm-sim
        path: /usr/bin/llvm-sim-{{ cpp_llvm_version }}
      - name: llvm-size
        link: /usr/bin/llvm-size
        path: /usr/bin/llvm-size-{{ cpp_llvm_version }}
      - name: llvm-split
        link: /usr/bin/llvm-split
        path: /usr/bin/llvm-split-{{ cpp_llvm_version }}
      - name: llvm-stress
        link: /usr/bin/llvm-stress
        path: /usr/bin/llvm-stress-{{ cpp_llvm_version }}
      - name: llvm-strings
        link: /usr/bin/llvm-strings
        path: /usr/bin/llvm-strings-{{ cpp_llvm_version }}
      - name: llvm-strip
        link: /usr/bin/llvm-strip
        path: /usr/bin/llvm-strip-{{ cpp_llvm_version }}
      - name: llvm-symbolizer
        link: /usr/bin/llvm-symbolizer
        path: /usr/bin/llvm-symbolizer-{{ cpp_llvm_version }}
      - name: llvm-tapi-diff
        link: /usr/bin/llvm-tapi-diff
        path: /usr/bin/llvm-tapi-diff-{{ cpp_llvm_version }}
      - name: llvm-tblgen
        link: /usr/bin/llvm-tblgen
        path: /usr/bin/llvm-tblgen-{{ cpp_llvm_version }}
      - name: llvm-tli-checker
        link: /usr/bin/llvm-tli-checker
        path: /usr/bin/llvm-tli-checker-{{ cpp_llvm_version }}
      - name: llvm-undname
        link: /usr/bin/llvm-undname
        path: /usr/bin/llvm-undname-{{ cpp_llvm_version }}
      - name: llvm-windres
        link: /usr/bin/llvm-windres
        path: /usr/bin/llvm-windres-{{ cpp_llvm_version }}
      - name: llvm-xray
        link: /usr/bin/llvm-xray
        path: /usr/bin/llvm-xray-{{ cpp_llvm_version }}
      - name: modularize
        link: /usr/bin/modularize
        path: /usr/bin/modularize-{{ cpp_llvm_version }}
      - name: not
        link: /usr/bin/not
        path: /usr/bin/not-{{ cpp_llvm_version }}
      - name: obj2yaml
        link: /usr/bin/obj2yaml
        path: /usr/bin/obj2yaml-{{ cpp_llvm_version }}
      - name: opt
        link: /usr/bin/opt
        path: /usr/bin/opt-{{ cpp_llvm_version }}
      - name: pp-trace
        link: /usr/bin/pp-trace
        path: /usr/bin/pp-trace-{{ cpp_llvm_version }}
      - name: sancov
        link: /usr/bin/sancov
        path: /usr/bin/sancov-{{ cpp_llvm_version }}
      - name: sanstats
        link: /usr/bin/sanstats
        path: /usr/bin/sanstats-{{ cpp_llvm_version }}
      - name: scan-build
        link: /usr/bin/scan-build
        path: /usr/bin/scan-build-{{ cpp_llvm_version }}
      - name: scan-build-py
        link: /usr/bin/scan-build-py
        path: /usr/bin/scan-build-py-{{ cpp_llvm_version }}
      - name: scan-view
        link: /usr/bin/scan-view
        path: /usr/bin/scan-view-{{ cpp_llvm_version }}
      - name: split-file
        link: /usr/bin/split-file
        path: /usr/bin/split-file-{{ cpp_llvm_version }}
      - name: verify-uselistorder
        link: /usr/bin/verify-uselistorder
        path: /usr/bin/verify-uselistorder-{{ cpp_llvm_version }}
      - name: wasm-ld
        link: /usr/bin/wasm-ld
        path: /usr/bin/wasm-ld-{{ cpp_llvm_version }}
      - name: yaml-bench
        link: /usr/bin/yaml-bench
        path: /usr/bin/yaml-bench-{{ cpp_llvm_version }}
      - name: yaml2obj
        link: /usr/bin/yaml2obj
        path: /usr/bin/yaml2obj-{{ cpp_llvm_version }}

- name: Update clang++ alternatives
  become: true
  community.general.alternatives:
    name: clang++
    link: /usr/bin/clang++
    path: /usr/bin/clang++-{{ cpp_llvm_version }}
    priority: "{{ cpp_llvm_version }}0"

- name: Update clang-format alternatives
  become: true
  community.general.alternatives:
    name: clang-format
    link: /usr/bin/clang-format
    path: /usr/bin/clang-format-{{ cpp_llvm_version }}
    priority: "{{ cpp_llvm_version }}0"
    subcommands:
      - name: clang-format-diff
        link: /usr/bin/clang-format-diff
        path: /usr/bin/clang-format-diff-{{ cpp_llvm_version }}

- name: Update clang-tidy alternatives
  become: true
  community.general.alternatives:
    name: clang-tidy
    link: /usr/bin/clang-tidy
    path: /usr/bin/clang-tidy-{{ cpp_llvm_version }}
    priority: "{{ cpp_llvm_version }}0"
    subcommands:
      - name: clang-tidy-diff.py
        link: /usr/bin/clang-tidy-diff.py
        path: /usr/bin/clang-tidy-diff-{{ cpp_llvm_version }}.py

- name: Update run-clang-tidy alternatives
  become: true
  community.general.alternatives:
    name: run-clang-tidy
    link: /usr/bin/run-clang-tidy
    path: /usr/bin/run-clang-tidy-{{ cpp_llvm_version }}
    priority: "{{ cpp_llvm_version }}0"
    subcommands:
      - name: run-clang-tidy.py
        link: /usr/bin/run-clang-tidy.py
        path: /usr/bin/run-clang-tidy-{{ cpp_llvm_version }}.py
