- name: Include Ubuntu gcc tasks
  ansible.builtin.include_tasks:
    file: gcc.yaml
  when: ansible_distribution == 'Ubuntu'

- name: Include Ubuntu llvm tasks
  ansible.builtin.include_tasks:
    file: llvm.yaml
  when: ansible_distribution == 'Ubuntu'

# Did not find a way to install custom compilers versions
- name: Install gcc on Fedora
  become: true
  ansible.builtin.dnf:
    name:
      - gcc
      - g++
  when: ansible_distribution == 'Fedora'

- name: Install llvm on Fedora
  become: true
  ansible.builtin.dnf:
    name:
      - clang-devel
      - libomp-devel
      - libunwind-devel
      - lld-devel
      - lldb-devel
      - llvm-devel
  when: ansible_distribution == 'Fedora'

- name: Include cmake tasks
  ansible.builtin.include_tasks:
    file: cmake.yaml

- name: Include vcpkg tasks
  ansible.builtin.include_tasks:
    file: vcpkg.yaml

- name: Install common C++ tools
  become: true
  ansible.builtin.package:
    name:
      - "{{ {'Ubuntu': 'build-essential', 'Fedora': 'kernel-devel'}[ansible_distribution] }}"
      - automake
      - bison
      - ccache
      - flex
      - gdb
      - make
      - ninja-build
      - valgrind

- name: Create symlink to fish config of {{ role_name }}
  ansible.builtin.file:
    src: "{{ role_host_path }}/files/{{ role_name }}.fish"
    dest: "{{ home }}/.config/fish/conf.d/{{ role_name }}.fish"
    state: link

- name: Set up bash
  ansible.builtin.lineinfile:
    path: "{{ home }}/.bashrc"
    regexp: "source .*/{{ role_name }}/files"
    line: source {{ role_host_path }}/files/bash.sh
    create: true
    mode: "0o644"
