# yamllint disable rule:line-length

# This file describes links and versions for the different components,
# which are used in this configuration.
# It is important to pin specific versions to ensure reproducibility.
#
# Most of the packages follow predicable patterns with arch and package formats.
# This is very useful, since it allows to compactly write down the url with some ansible templating.
# An update procedure is also aware of these simple patterns.
# Some packages, however, do not have predicable URL patterns.
# Writing an update procedure, which would adapt for complex templating, is cumbersome.
# To overcome this, here we use a two-staged manifest variable, which works according to the following rules:
# 1. If the component has a predicable URL pattern, include it directly into the `manifest` variable.
#    Essentially, we have written several different URLs with one templated entry.
#    Update procedure is following simple patterns and is able to update such entry.
#    Playbook tasks will be able to reference this entry directly without disambiguating different
#    variants themselves.
# 2. If the component does not have a predicable URL pattern, explicilty "expand" it into the several
#    variants in the `manifest_pre` variable.
#    These variants must follow simple patterns and will be updated one-by-one by the update procedure.
#    The final complex-templated variable should be included in the `manifest` variable and
#    it will not be touched by the update procedure.

deb_arch: "{{ {'aarch64': 'arm64', 'x86_64': 'amd64'}[ansible_architecture] }}" # noqa: var-naming[no-role-prefix]
pack: "{{ {'Ubuntu': 'deb', 'Fedora': 'rpm'}[ansible_distribution] }}" # noqa: var-naming[no-role-prefix]
pack_arch: "{{ {'Ubuntu': deb_arch, 'Fedora': ansible_architecture}[ansible_distribution] }}" # noqa: var-naming[no-role-prefix]

manifest_pre:
  hiddify:
    rpm: https://github.com/hiddify/hiddify-next/releases/download/v2.0.5/Hiddify-rpm-x64.rpm
    deb: https://github.com/hiddify/hiddify-next/releases/download/v2.0.5/Hiddify-Debian-x64.{{ pack }}
  turbovnc:
    rpm: https://github.com/TurboVNC/turbovnc/releases/download/3.1.3/turbovnc-3.1.3.{{ ansible_architecture }}.rpm
    deb: https://github.com/TurboVNC/turbovnc/releases/download/3.1.3/turbovnc_3.1.3_{{ pack_arch }}.{{ pack }}

manifest: # noqa: var-naming[no-role-prefix]
  clipboard:
    url: https://github.com/equalsraf/win32yank/releases/download/v0.1.1/win32yank-x64.zip
  cmake:
    url: https://github.com/Kitware/CMake/releases/download/v3.31.3/cmake-3.31.3-linux-{{ ansible_architecture }}.sh
  drawio:
    url: https://github.com/jgraph/drawio-desktop/releases/download/v25.0.2/drawio-{{ pack_arch }}-25.0.2.{{ pack }}
  firacode:
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/FiraCode.zip
  fzf:
    url: https://github.com/junegunn/fzf.git
    version: b8d2b0df7e1241c09eff21dbb63ebcc841efc824
  hiddify:
    url: "{{ {'Ubuntu': manifest_pre.hiddify.deb, 'Fedora': manifest_pre.hiddify.rpm}[ansible_distribution] }}"
  kitty_themes:
    url: https://github.com/kovidgoyal/kitty-themes.git
    version: 1d379066fc44f58f4131421c31290bb8c82178d5
  lazygit:
    url: https://github.com/jesseduffield/lazygit/releases/download/v0.44.1/lazygit_0.44.1_Linux_{{ ansible_architecture }}.tar.gz
  neovim:
    url: https://github.com/neovim/neovim/releases/download/v0.10.3/nvim-linux64.tar.gz
  nixfmt:
    url: https://github.com/NixOS/nixfmt/releases/download/v0.6.0/nixfmt-x86_64-linux
  nvchad2:
    url: https://github.com/NvChad/NvChad
    version: e5f8a38ae3d6b3bedf68f29b0e96dad7a4ca2da5
    lock: true
  stylua:
    url: https://github.com/JohnnyMorganz/StyLua/releases/download/v2.0.2/stylua-linux-{{ ansible_architecture }}.zip
  tpm:
    url: https://github.com/tmux-plugins/tpm
    version: 99469c4a9b1ccf77fade25842dc7bafbc8ce9946
  turbovnc:
    url: "{{ {'Ubuntu': manifest_pre.turbovnc.deb, 'Fedora': manifest_pre.turbovnc.rpm}[ansible_distribution] }}"
  vcpkg:
    url: https://github.com/microsoft/vcpkg
    version: 80d54ff62d528339c626a6fbc3489a7f25956ade
  yazi:
    url: https://github.com/sxyazi/yazi/releases/download/v0.4.2/yazi-{{ ansible_architecture }}-unknown-linux-musl.zip
