manifest:
  ansible_community_general:
    url: https://github.com/ansible-collections/community.general
    version: 7.2.1
  ansible_containers_podman:
    url: https://github.com/containers/ansible-podman-collections
    version: 1.10.2
  ansible_posix:
    url: https://github.com/ansible-collections/ansible.posix
    version: 1.5.4
  bat:
    url: https://github.com/sharkdp/bat/releases/download/v0.23.0/bat-musl_0.23.0_amd64.deb
  clipboard:
    url: https://github.com/equalsraf/win32yank/releases/download/v0.1.1/win32yank-x64.zip
  cmake:
    url: https://github.com/Kitware/CMake/releases/download/v3.27.1/cmake-3.27.1-linux-x86_64.sh
  drawio:
    url: https://github.com/jgraph/drawio-desktop/releases/download/v21.6.5/drawio-amd64-21.6.5.deb
  fd:
    url: https://github.com/sharkdp/fd/releases/download/v8.7.0/fd-musl_8.7.0_amd64.deb
  firacode:
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/FiraCode.zip
  fzf:
    url: https://github.com/junegunn/fzf.git
    version: 84a9c2c1122470b0b67b8e20e074704539bc1fc4
  github_cli:
    url: https://github.com/cli/cli/releases/download/v2.32.1/gh_2.32.1_linux_amd64.deb
  kitty_themes:
    url: https://github.com/kovidgoyal/kitty-themes.git
    version: b6598362df9ee042ab700f96db9d51ccb16cc7ce
  neovim:
    url: https://github.com/neovim/neovim/releases/download/v0.9.1/nvim-linux64.tar.gz
  nvchad2:
    url: https://github.com/NvChad/NvChad
    version: 487ca445665d6d0a9b25f7e367c6a9a300505c9e
  rg:
    url: https://github.com/BurntSushi/ripgrep/releases/download/13.0.0/ripgrep_13.0.0_amd64.deb
  tpm:
    url: https://github.com/tmux-plugins/tpm
    version: 99469c4a9b1ccf77fade25842dc7bafbc8ce9946
  vcpkg:
    url: https://github.com/microsoft/vcpkg
    version: 247662ef304453c72acd6b520fa7ff7656e7347c
