manifest:
  ansible_community_general:
    url: https://github.com/ansible-collections/community.general
    version: 7.1.0
  ansible_containers_podman:
    url: https://github.com/containers/ansible-podman-collections
    version: 1.10.2
  ansible_posix:
    url: https://github.com/ansible-collections/ansible.posix
    version: 1.5.4
  bat:
    url: https://github.com/sharkdp/bat/releases/download/v0.23.0/bat-musl_0.23.0_amd64.deb
  clipboard:
    url: https://github.com/equalsraf/win32yank/releases/download/v0.1.1/win32yank-x64.zip
  cmake:
    url: https://github.com/Kitware/CMake/releases/download/v3.26.4/cmake-3.26.4-linux-x86_64.sh
  drawio:
    url: https://github.com/jgraph/drawio-desktop/releases/download/v21.5.0/drawio-amd64-21.5.0.deb
  fd:
    url: https://github.com/sharkdp/fd/releases/download/v8.7.0/fd-musl_8.7.0_amd64.deb
  firacode:
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/FiraCode.zip
    lock: true
  fzf:
    url: https://github.com/junegunn/fzf.git
    version: 01302d097c39c3429de65424c6adb75fcac82187
  github_cli:
    url: https://github.com/cli/cli/releases/download/v2.31.0/gh_2.31.0_linux_amd64.deb
  kitty_themes:
    url: https://github.com/kovidgoyal/kitty-themes.git
    version: 9a30b1b123c6d076aedcb1b6f1dbc55c35b4e5d1
  neovim:
    url: https://github.com/neovim/neovim/releases/download/v0.9.1/nvim-linux64.tar.gz
  nvchad2:
    url: https://github.com/NvChad/NvChad
    version: 286c951d7b1f4531c8f40873a3846f40a3503e33
  rg:
    url: https://github.com/BurntSushi/ripgrep/releases/download/13.0.0/ripgrep_13.0.0_amd64.deb
  tpm:
    url: https://github.com/tmux-plugins/tpm
    version: 99469c4a9b1ccf77fade25842dc7bafbc8ce9946
  vcpkg:
    url: https://github.com/microsoft/vcpkg
    version: 288e8bebf4ca67c1f8ebd49366b03650cfd9eb7d
  wezterm:
    url: >
      https://github.com/wez/wezterm/releases/download/20230408-112425-69ae8472/wezterm-20230408-112425-69ae8472.Ubuntu22.04.deb
