# yamllint disable rule:line-length

# This file describes links and versions for the different components,
# which are used in this configuration.
# It is important to pin specific versions to ensure reproducibility.
#
# Most of the packages follow predictable patterns with arch and package formats.
# This is very useful, since it allows to compactly write down the url with some ansible templating.
# An update procedure is also aware of these simple patterns.
# Some packages, however, do not have predicable URL patterns.
# Writing an update procedure, which would adapt for complex templating, is cumbersome.
# To overcome this, here we use a two-staged manifest variable, which works according to the following rules:
# 1. If the component has a predicable URL pattern, include it directly into the `manifest` variable.
#    Essentially, we have written several different URLs with one templated entry.
#    Update procedure is following simple patterns and is able to update such entry.
#    Playbook tasks will be able to reference this entry directly without disambiguating different
#    variants themselves.
# 2. If the component does not have a predicable URL pattern, explicitly "expand" it into the several
#    variants in the `manifest_pre` variable.
#    These variants must follow simple patterns and will be updated one-by-one by the update procedure.
#    The final complex-templated variable should be included in the `manifest` variable and
#    it will not be touched by the update procedure.

deb_arch: "{{ {'aarch64': 'arm64', 'x86_64': 'amd64'}[ansible_architecture] }}" # noqa: var-naming[no-role-prefix]
pack: "{{ {'Ubuntu': 'deb', 'Fedora': 'rpm'}[ansible_distribution] }}" # noqa: var-naming[no-role-prefix]
pack_arch: "{{ {'Ubuntu': deb_arch, 'Fedora': ansible_architecture}[ansible_distribution] }}" # noqa: var-naming[no-role-prefix]

manifest_pre:
  hiddify:
    rpm:
      url: https://github.com/hiddify/hiddify-next/releases/download/v2.0.5/Hiddify-rpm-x64.rpm
    deb:
      url: https://github.com/hiddify/hiddify-next/releases/download/v2.0.5/Hiddify-Debian-x64.{{ pack }}
  turbovnc:
    rpm:
      url: https://github.com/TurboVNC/turbovnc/releases/download/3.1.4/turbovnc-3.1.4.{{ ansible_architecture }}.rpm
    deb:
      url: https://github.com/TurboVNC/turbovnc/releases/download/3.1.4/turbovnc_3.1.4_{{ pack_arch }}.{{ pack }}

manifest: # noqa: var-naming[no-role-prefix]
  carapace:
    url: https://github.com/carapace-sh/carapace-bin/releases/download/v1.3.1/carapace-bin_1.3.1_linux_{{ deb_arch }}.tar.gz
  clipboard:
    url: https://github.com/equalsraf/win32yank/releases/download/v0.1.1/win32yank-x64.zip
  cmake:
    url: https://github.com/Kitware/CMake/releases/download/v4.0.1/cmake-4.0.1-linux-{{ ansible_architecture }}.sh
  delta:
    url: https://github.com/dandavison/delta/releases/download/0.18.2/delta-0.18.2-{{ ansible_architecture }}-unknown-linux-musl.tar.gz
  dua:
    url: https://github.com/Byron/dua-cli/releases/download/v2.30.1/dua-v2.30.1-{{ ansible_architecture }}-unknown-linux-musl.tar.gz
  dust:
    url: https://github.com/bootandy/dust/releases/download/v1.2.0/dust-v1.2.0-{{ ansible_architecture }}-unknown-linux-musl.tar.gz
  fish:
    url: https://github.com/fish-shell/fish-shell/releases/download/4.0.2/fish-static-{{ deb_arch }}-4.0.2.tar.xz
  gh:
    url: https://github.com/cli/cli/releases/download/v2.72.0/gh_2.72.0_linux_{{ deb_arch }}.tar.gz
  gitleaks:
    url: https://github.com/gitleaks/gitleaks/releases/download/v8.27.2/gitleaks_8.27.2_linux_x64.tar.gz
  drawio:
    url: https://github.com/jgraph/drawio-desktop/releases/download/v26.2.15/drawio-{{ pack_arch }}-26.2.15.{{ pack }}
  eza:
    url: https://github.com/eza-community/eza/releases/download/v0.21.3/eza_{{ ansible_architecture }}-unknown-linux-musl.tar.gz
  fzf:
    url: https://github.com/junegunn/fzf.git
    version: 9c1a47acf7453f9dad5905b7f23ad06e5195d51f
  hiddify:
    url: "{{ manifest_pre.hiddify[pack].url }}"
  jetbrains_mono:
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/JetBrainsMono.tar.xz
  kitty_themes:
    url: https://github.com/kovidgoyal/kitty-themes.git
    version: 49d0a9199d64cbeb7bcf7db1a04d164ee0c16e1b
  lazygit:
    url: https://github.com/jesseduffield/lazygit/releases/download/v0.50.0/lazygit_0.50.0_Linux_{{ ansible_architecture }}.tar.gz
  neovim:
    url: https://github.com/neovim/neovim/releases/download/v0.11.1/nvim-linux-{{ ansible_architecture }}.tar.gz
  nixfmt:
    url: https://github.com/NixOS/nixfmt/releases/download/v0.6.0/nixfmt-{{ ansible_architecture }}-linux
  nu:
    url: https://github.com/nushell/nushell/releases/download/0.104.0/nu-0.104.0-{{ ansible_architecture }}-unknown-linux-musl.tar.gz
  oh_my_posh:
    url: https://github.com/JanDeDobbeleer/oh-my-posh/releases/download/v25.23.3/posh-linux-{{ deb_arch }}
  oh_my_posh_themes:
    url: https://github.com/JanDeDobbeleer/oh-my-posh/releases/download/v25.23.3/themes.zip
  sops:
    url: https://github.com/getsops/sops/releases/download/v3.10.2/sops-v3.10.2.linux.{{ deb_arch }}
  stylua:
    url: https://github.com/JohnnyMorganz/StyLua/releases/download/v2.1.0/stylua-linux-{{ ansible_architecture }}.zip
  tpm:
    url: https://github.com/tmux-plugins/tpm
    version: 99469c4a9b1ccf77fade25842dc7bafbc8ce9946
  turbovnc:
    url: "{{ manifest_pre.turbovnc[pack].url }}"
  vcpkg:
    url: https://github.com/microsoft/vcpkg
    version: 41c447cc210dc39aa85d4a5f58b4a1b9e573b3dc
  wiki:
    url: https://github.com/Builditluc/wiki-tui/releases/download/v0.9.1/wiki-tui-linux.tar.gz
  xh:
    url: https://github.com/ducaale/xh/releases/download/v0.24.1/xh-v0.24.1-{{ ansible_architecture }}-unknown-linux-musl.tar.gz
  yazi:
    url: https://github.com/sxyazi/yazi/releases/download/v25.4.8/yazi-{{ ansible_architecture }}-unknown-linux-musl.zip
  zls:
    url: https://github.com/zigtools/zls/releases/download/0.14.0/zls-{{ ansible_architecture }}-linux.tar.xz
  zig:
    url: https://ziglang.org/download/0.14.0/zig-linux-{{ ansible_architecture }}-0.14.0.tar.xz
