# yamllint disable rule:line-length

# This file describes links and versions for the different components,
# which are used in this configuration.
# It is important to pin specific versions to ensure reproducibility.
#
# Most of the packages follow predicable patterns with arch and package formats.
# This is very useful, since it allows to compactly write down the url with some ansible templating.
# An update procedure is also aware of these simple patterns.
# Some packages, however, do not have predicable URL patterns.
# Writing an update procedure, which would adapt for complex templating, is cumbersome.
# To overcome this, here we use a two-staged manifest variable, which works according to the following rules:
# 1. If the component has a predicable URL pattern, include it directly into the `manifest` variable.
#    Essentially, we have written several different URLs with one templated entry.
#    Update procedure is following simple patterns and is able to update such entry.
#    Playbook tasks will be able to reference this entry directly without disambiguating different
#    variants themselves.
# 2. If the component does not have a predicable URL pattern, explicilty "expand" it into the several
#    variants in the `manifest_pre` variable.
#    These variants must follow simple patterns and will be updated one-by-one by the update procedure.
#    The final complex-templated variable should be included in the `manifest` variable and
#    it will not be touched by the update procedure.

deb_arch: "{{ {'aarch64': 'arm64', 'x86_64': 'amd64'}[ansible_architecture] }}" # noqa: var-naming[no-role-prefix]
pack: "{{ {'Ubuntu': 'deb', 'Fedora': 'rpm'}[ansible_distribution] }}" # noqa: var-naming[no-role-prefix]
pack_arch: "{{ {'Ubuntu': deb_arch, 'Fedora': ansible_architecture}[ansible_distribution] }}" # noqa: var-naming[no-role-prefix]

manifest_pre:

manifest: # noqa: var-naming[no-role-prefix]
  clipboard:
    url: https://github.com/equalsraf/win32yank/releases/download/v0.1.1/win32yank-x64.zip
  cmake:
    url: https://github.com/Kitware/CMake/releases/download/v3.30.0/cmake-3.30.0-linux-{{ ansible_architecture }}.sh
  drawio:
    url: https://github.com/jgraph/drawio-desktop/releases/download/v24.6.4/drawio-{{ pack_arch }}-24.6.4.{{ pack }}
  firacode:
    lock: true
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/FiraCode.zip
  fzf:
    url: https://github.com/junegunn/fzf.git
    version: b44ab9e33c236787bcd00b655cae4a8ef8497059
  kitty_themes:
    url: https://github.com/kovidgoyal/kitty-themes.git
    version: 522b2bc8631cfe28a1b230d1b774f911eab17cf3
  lazygit:
    url: https://github.com/jesseduffield/lazygit/releases/download/v0.42.0/lazygit_0.42.0_Linux_{{ ansible_architecture }}.tar.gz
  neovim:
    url: https://github.com/neovim/neovim/releases/download/v0.10.0/nvim-linux64.tar.gz
  nvchad2:
    url: https://github.com/NvChad/NvChad
    version: e5f8a38ae3d6b3bedf68f29b0e96dad7a4ca2da5
    lock: true
  stylua:
    url: https://github.com/JohnnyMorganz/StyLua/releases/download/v0.20.0/stylua-linux-{{ ansible_architecture }}.zip
  tpm:
    url: https://github.com/tmux-plugins/tpm
    version: 99469c4a9b1ccf77fade25842dc7bafbc8ce9946
  vcpkg:
    url: https://github.com/microsoft/vcpkg
    version: 576379156e82da642f8d1834220876759f13534d
  yazi:
    url: https://github.com/sxyazi/yazi/releases/download/v0.2.5/yazi-{{ ansible_architecture }}-unknown-linux-musl.zip
