manifest:
  ansible_community_general:
    url: https://github.com/ansible-collections/community.general
    version: 7.4.0
  ansible_containers_podman:
    url: https://github.com/containers/ansible-podman-collections
    version: 1.10.3
  ansible_posix:
    url: https://github.com/ansible-collections/ansible.posix
    version: 1.5.4
  bat:
    url: https://github.com/sharkdp/bat/releases/download/v0.23.0/bat-musl_0.23.0_amd64.deb
  clipboard:
    url: https://github.com/equalsraf/win32yank/releases/download/v0.1.1/win32yank-x64.zip
  cmake:
    url: https://github.com/Kitware/CMake/releases/download/v3.27.4/cmake-3.27.4-linux-x86_64.sh
  drawio:
    url: https://github.com/jgraph/drawio-desktop/releases/download/v21.6.8/drawio-amd64-21.6.8.deb
  fd:
    url: https://github.com/sharkdp/fd/releases/download/v8.7.0/fd-musl_8.7.0_amd64.deb
  firacode:
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/FiraCode.zip
  fzf:
    url: https://github.com/junegunn/fzf.git
    version: eb4bbf32948303e326a2791c6a875f32d7b5c97f
  github_cli:
    url: https://github.com/cli/cli/releases/download/v2.34.0/gh_2.34.0_linux_amd64.deb
  kitty_themes:
    url: https://github.com/kovidgoyal/kitty-themes.git
    version: d734f0babc18e0b9318caf6c48125ebdedd95c45
  neovim:
    url: https://github.com/neovim/neovim/releases/download/v0.9.1/nvim-linux64.tar.gz
  nvchad2:
    url: https://github.com/NvChad/NvChad
    version: 215aa2bb2ff702014132c629d9c995246234fe0e
  rg:
    url: https://github.com/BurntSushi/ripgrep/releases/download/13.0.0/ripgrep_13.0.0_amd64.deb
  tpm:
    url: https://github.com/tmux-plugins/tpm
    version: 99469c4a9b1ccf77fade25842dc7bafbc8ce9946
  vcpkg:
    url: https://github.com/microsoft/vcpkg
    version: 2c401863dd54a640aeb26ed736c55489c079323b
