manifest:
  ansible_community_general:
    url: https://github.com/ansible-collections/community.general
    version: 8.2.0
  ansible_containers_podman:
    url: https://github.com/containers/ansible-podman-collections
    version: 1.11.0
  ansible_posix:
    url: https://github.com/ansible-collections/ansible.posix
    version: 1.5.4
  bat:
    url: https://github.com/sharkdp/bat/releases/download/v0.24.0/bat-musl_0.24.0_amd64.deb
  clipboard:
    url: https://github.com/equalsraf/win32yank/releases/download/v0.1.1/win32yank-x64.zip
  cmake:
    url: https://github.com/Kitware/CMake/releases/download/v3.28.1/cmake-3.28.1-linux-x86_64.sh
  drawio:
    url: https://github.com/jgraph/drawio-desktop/releases/download/v22.1.16/drawio-amd64-22.1.16.deb
  fd:
    url: https://github.com/sharkdp/fd/releases/download/v9.0.0/fd-musl_9.0.0_amd64.deb
  firacode:
    lock: true
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/FiraCode.zip
  fzf:
    url: https://github.com/junegunn/fzf.git
    version: 20240101197348a78db5a1dac945a2dff6a4e654
  github_cli:
    url: https://github.com/cli/cli/releases/download/v2.40.1/gh_2.40.1_linux_amd64.deb
  kitty_themes:
    url: https://github.com/kovidgoyal/kitty-themes.git
    version: 46d9dfe230f315a6a0c62f4687f6b3da20fd05e4
  lazygit:
    url: https://github.com/jesseduffield/lazygit/releases/download/v0.40.2/lazygit_0.40.2_Linux_x86_64.tar.gz
  neovim:
    url: https://github.com/neovim/neovim/releases/download/v0.9.5/nvim-linux64.tar.gz
  nvchad2:
    url: https://github.com/NvChad/NvChad
    version: c2ec317b1bbcac75b7c258759b62c65261ab5d5d
  rg:
    url: https://github.com/BurntSushi/ripgrep/releases/download/14.0.3/ripgrep_14.0.3-1_amd64.deb
  stylua:
    url: https://github.com/JohnnyMorganz/StyLua/releases/download/v0.19.1/stylua-linux-x86_64.zip
  tpm:
    url: https://github.com/tmux-plugins/tpm
    version: 99469c4a9b1ccf77fade25842dc7bafbc8ce9946
  vcpkg:
    url: https://github.com/microsoft/vcpkg
    version: 64e15f6669480b2d2bff1e5e815c571a8213421e
