deb_arch: "{{ {'aarch64': 'arm64', 'x86_64': 'amd64'}[ansible_architecture] }}" # noqa: var-naming[no-role-prefix]
pack: "{{ {'Ubuntu': 'deb', 'Fedora': 'rpm'}[ansible_distribution] }}" # noqa: var-naming[no-role-prefix]
pack_arch: "{{ {'Ubuntu': deb_arch, 'Fedora': ansible_architecture}[ansible_distribution] }}" # noqa: var-naming[no-role-prefix] yaml[line-length]

manifest: # noqa: var-naming[no-role-prefix]
  clipboard:
    url: https://github.com/equalsraf/win32yank/releases/download/v0.1.1/win32yank-x64.zip
  cmake:
    url: https://github.com/Kitware/CMake/releases/download/v3.29.4/cmake-3.29.4-linux-{{ ansible_architecture }}.sh
  drawio:
    url: https://github.com/jgraph/drawio-desktop/releases/download/v24.4.13/drawio-{{ pack_arch }}-24.4.13.{{ pack }}
  firacode:
    lock: true
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/FiraCode.zip
  fzf:
    url: https://github.com/junegunn/fzf.git
    version: 3ee1fc203406debab432dbf3cb67f37ea7cb3d30
  kitty_themes:
    url: https://github.com/kovidgoyal/kitty-themes.git
    version: 891ca835de3112e69f1dfc87fd6cfab354a30f25
  lazygit:
    url: https://github.com/jesseduffield/lazygit/releases/download/v0.42.0/lazygit_0.42.0_Linux_{{ ansible_architecture }}.tar.gz # noqa: yaml[line-length]
  neovim:
    url: https://github.com/neovim/neovim/releases/download/v0.10.0/nvim-linux64.tar.gz
  nvchad2:
    url: https://github.com/NvChad/NvChad
    version: e5f8a38ae3d6b3bedf68f29b0e96dad7a4ca2da5
    lock: true
  stylua:
    url: https://github.com/JohnnyMorganz/StyLua/releases/download/v0.20.0/stylua-linux-{{ ansible_architecture }}.zip
  tpm:
    url: https://github.com/tmux-plugins/tpm
    version: 99469c4a9b1ccf77fade25842dc7bafbc8ce9946
  vcpkg:
    url: https://github.com/microsoft/vcpkg
    version: 67cc1677c3bf5c23ea14b9d2416c7422fdeac492
  yazi:
    url: https://github.com/sxyazi/yazi/releases/download/v0.2.5/yazi-{{ ansible_architecture }}-unknown-linux-musl.zip
