- name: Add nodejs gpg key
  become: true
  ansible.builtin.get_url:
    url: "{{ nodejs_gpg }}"
    dest: /etc/apt/trusted.gpg.d/nodejs.asc

- name: Add nodejs repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/nodejs.asc] {{ nodejs_repo }} {{ ansible_distribution_release
      }} main

- name: Install nodejs
  become: true
  ansible.builtin.apt:
    name:
      - nodejs
