- name: Add nodejs gpg key
  become: true
  ansible.builtin.get_url:
    url: "{{ nodejs_gpg }}"
    dest: "{{ apt_keys }}/nodejs.gpg.key"
    mode: "0o644"

- name: Add nodejs repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by={{ apt_keys }}/nodejs.gpg.key] {{ nodejs_repo }} nodistro main

- name: Install nodejs
  become: true
  ansible.builtin.apt:
    name:
      - nodejs
