- name: Install xkb-data
  become: true
  ansible.builtin.package:
    name: "{{ {'Ubuntu': 'xkb-data', 'Fedora': 'xkeyboard-config'}[ansible_distribution] }}"

- name: Copy rnk keyboard
  become: true
  ansible.builtin.copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: /usr/share/X11/xkb/symbols/{{ item }}
    owner: root
    group: root
    mode: "0o644"
  register: keyboard_layouts_rnk
  loop:
    - en_rnk
    - ru_rnk

- name: Insert layout entry to evdev.xml
  become: true
  ansible.builtin.blockinfile:
    path: /usr/share/X11/xkb/rules/evdev.xml
    block: "{{ lookup('ansible.builtin.file', '{{ role_path }}/files/evdev.xml') }}"
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK FOR {{ role_name }} -->"
    insertbefore: '\</layoutList\>'
  register: keyboard_layouts_evdev

- name: Reconfigure xkb-data
  become: true
  changed_when: keyboard_layouts_rnk is changed or keyboard_layouts_evdev is changed
  ansible.builtin.command: dpkg-reconfigure xkb-data
  when: ansible_distribution == 'Ubuntu'
