[metadata]
name = "text"
description = "A channel to find and select text from files"
requirements = ["rg", "bat"]

[source]
command = [
  # 1. No hidden, respect ignore.
  """rg . \
  --ignore-file "${XDG_CONFIG_HOME:-$HOME/.config}/television/ignore" \
  --follow \
  --no-heading \
  --line-number \
  --colors 'match:fg:white' \
  --colors 'path:fg:blue' \
  --color=always \
  """,

  # 2. Hidden, respect ignore, manual excludes.
  """rg . \
  --hidden \
  --ignore-file "${XDG_CONFIG_HOME:-$HOME/.config}/television/ignore" \
  --follow \
  --no-heading \
  --line-number \
  --colors 'match:fg:white' \
  --colors 'path:fg:blue' \
  --color=always \
  """,

  # 3. Hidden, no ignore, manual excludes.
  """rg . \
  --hidden \
  --no-ignore \
  --ignore-file "${XDG_CONFIG_HOME:-$HOME/.config}/television/ignore" \
  --follow \
  --no-heading \
  --line-number \
  --colors 'match:fg:white' \
  --colors 'path:fg:blue' \
  --color=always \
  """,

  # 4. Hidden, no ignore.
  """rg . \
  --hidden \
  --no-ignore \
  --follow \
  --no-heading \
  --line-number \
  --colors 'match:fg:white' \
  --colors 'path:fg:blue' \
  --color=always \
  """,
]
ansi = true
frecency = false
output = "{strip_ansi|split:\\::..2}"
shell = "bash"

[preview]
command = "bat -n --color=always '{strip_ansi|split:\\::0}'"
offset = '{strip_ansi|split:\::1}'

[ui]
preview_panel = { header = '{strip_ansi|split:\::..2}' }

[keybindings]
shortcut = "ctrl-q"
enter = "actions:edit"
ctrl-o = "actions:edit"

[actions.edit]
description = "Open file in editor at line"
command = "${EDITOR:-vim} '+{strip_ansi|split:\\::1}' '{strip_ansi|split:\\::0}'"
shell = "bash"
mode = "execute"
