- name: Install ssh tools
  become: true
  ansible.builtin.apt:
    name:
      - libssl-dev
      - openssh-client
      - openssh-server
      - sshpass

- name: Create ~/.ssh directory
  ansible.builtin.file:
    path: "{{ home }}/.ssh"
    state: directory
    mode: 0755

- name: List decrypted private keys
  ansible.builtin.find:
    paths: "{{ ssh_path }}"
    patterns: '*rsa'
  register: rsa_keys

- name: Create symlinks to ssh private keys
  ansible.builtin.file:
    src: "{{ item.path }}"
    dest: "{{ home }}/.ssh/{{ item.path | basename }}"
    state: link
    mode: 0600
  loop: "{{ rsa_keys.files }}"
  loop_control:
    label: "{{ item.path | basename }}"

- name: List public keys
  ansible.builtin.find:
    paths: "{{ ssh_path }}"
    patterns: '*rsa.pub'
  register: rsa_pub_keys

- name: Create symlinks to ssh public keys
  ansible.builtin.file:
    src: "{{ item.path }}"
    dest: "{{ home }}/.ssh/{{ item.path | basename }}"
    state: link
    mode: 0644
  loop: "{{ rsa_pub_keys.files }}"
  loop_control:
    label: "{{ item.path | basename }}"

- name: Create symlink to {{ role_name }}.fish
  ansible.builtin.file:
    src: "{{ remote_role_path }}/files/{{ role_name }}.fish"
    dest: "{{ home }}/.config/fish/conf.d/{{ role_name }}.fish"
    state: link

- name: Enable public key authentication
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/ssh/sshd_config"
    regexp: '[ #]{0,10}PubkeyAuthentication \w*\s*$'
    line: PubkeyAuthentication yes

- name: Disable password authentication
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/ssh/sshd_config"
    regexp: '[ #]{0,10}PasswordAuthentication \w*\s*$'
    line: PasswordAuthentication no

- name: Disable keyboard interactive authentication
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/ssh/sshd_config"
    regexp: '[ #]{0,10}KbdInteractiveAuthentication \w*\s*$'
    line: KbdInteractiveAuthentication no
