- name: Install podman
  become: true
  ansible.builtin.package:
    name: podman

- name: Install podman completions
  ansible.builtin.shell: |
    podman completion bash --file {{ home }}/.local/share/bash-completion/completions/podman
    podman completion fish --file {{ home }}/.config/fish/completions/podman.fish
  args:
    executable: bash
  changed_when: false

- name: Set up bash
  ansible.builtin.lineinfile:
    path: "{{ home }}/.bashrc"
    regexp: "source .*/{{ role_name }}/files"
    line: source {{ role_host_path }}/files/bash.sh

- name: Create symlinks to fish functions
  ansible.builtin.file:
    src: "{{ role_host_path }}/files/fish_functions/{{ item | basename }}"
    dest: "{{ home }}/.config/fish/functions/{{ item | basename }}"
    state: link
  loop: "{{ lookup('fileglob', '{{ role_path }}/files/fish_functions/*', wantlist=True) }}"
