- name: Install fd
  become: true
  ansible.builtin.apt:
    deb: "{{ fd_url }}"
  retries: "{{ web_retries }}"
  delay: "{{ web_delay }}"
  register: installed
  until: installed is not failed

- name: Install bat
  become: true
  ansible.builtin.apt:
    deb: "{{ bat_url }}"
  retries: "{{ web_retries }}"
  delay: "{{ web_delay }}"
  register: installed
  until: installed is not failed

- name: Install ripgrep
  become: true
  ansible.builtin.apt:
    deb: "{{ rg_url }}"
  retries: "{{ web_retries }}"
  delay: "{{ web_delay }}"
  register: installed
  until: installed is not failed

- name: Download fzf
  ansible.builtin.git:
    repo: "{{ fzf_url }}"
    dest: "{{ home }}/.fzf"
    version: "{{ fzf_commit }}"
  register: fzf_download
  retries: "{{ web_retries }}"
  delay: "{{ web_delay }}"
  until: fzf_download is not failed

- name: Install fzf
  ansible.builtin.shell: |
    # Installing fish completion here will break custom settings
    # of the patrickf1/fzf.fish plugin
    "{{ home }}"/.fzf/install --all --no-fish
  changed_when: fzf_download is changed

- name: Install more utils
  become: true
  ansible.builtin.apt:
    name:
      - exa
      - jq
      - moreutils

- name: Download fisher
  ansible.builtin.get_url:
    url: https://git.io/fisher
    dest: "{{ home }}/.config/fish/functions/fisher.fish"
    mode: "0755"
  retries: "{{ web_retries }}"
  delay: "{{ web_delay }}"
  register: downloaded
  until: downloaded is not failed

- name: Create symlink to fish_plugins
  ansible.builtin.file:
    src: "{{ remote_role_path }}/files/fish_plugins"
    dest: "{{ home }}/.config/fish/fish_plugins"
    state: link
    force: true

- name: Install fisher plugins
  ansible.builtin.shell: |
    set -o pipefail
    set -x TERM xterm-256color
    fisher update
    echo 1 1 1 2 3 1 1 2 y | tide configure
  args:
    executable: fish
  changed_when: false

- name: Set up bash
  ansible.builtin.lineinfile:
    path: "{{ home }}/.bashrc"
    regexp: 'source .*/{{ role_name }}/files'
    line: source {{ remote_role_path }}/files/bash.sh

- name: Create symlink to {{ role_name }}.fish
  ansible.builtin.file:
    src: "{{ remote_role_path }}/files/{{ role_name }}.fish"
    dest: "{{ home }}/.config/fish/conf.d/{{ role_name }}.fish"
    state: link
    force: true

- name: Create symlinks to fish functions
  ansible.builtin.file:
    src: "{{ remote_role_path }}/files/fish_functions/{{ item | basename }}"
    dest: "{{ home }}/.config/fish/functions/{{ item | basename }}"
    state: link
    force: true
  loop: "{{ lookup('fileglob', '{{ role_path }}/files/fish_functions/*', wantlist=True) }}"
  register: functions

- name: Patch fzf - fix focus events and add ripgrep support
  ansible.posix.patch:
    src: "{{ role_path }}/files/fzf.fish.patch"
    basedir: "{{ home }}/.config/fish"
    strip: 1
  changed_when: functions is changed

- name: Configure fzf key bindings
  # C-a beginning of the line
  # C-b one char backwards
  # C-c interrupt process
  # C-d delete one char
  # C-e end of the line
  # C-f one char forward
  # C-g fzf git log
  # C-h goto left window
  # C-i show suggestions
  # C-j goto lower window
  # C-k goto upper window
  # C-l goto right window
  # C-m enter
  # C-n next history command
  # C-o fzf git status
  # C-p previous history command
  # C-q ???
  # C-r fzf command history
  # C-s tmux reserved
  # C-t fzf search files
  # C-u delete all to the left
  # C-v fzf search variables
  # C-w delete one word to the left
  # C-x fzf search processes (previously copy fish command)
  # C-y fzf search files with ripgrep (previously paste something)
  # C-z undo
  ansible.builtin.lineinfile:
    path: "{{ home }}/.config/fish/functions/fish_user_key_bindings.fish"
    regexp: 'fzf_configure_bindings'
    # Be aware that single-line yaml must not contain additional indents, otherwise it will be treated as newline.
    line: >
      fzf_configure_bindings
      --directory=\ct
      --git_log=\cg
      --git_status=\co
      --history=\cr
      --processes=\cx
      --variables=\cv
      --files=\cy
    create: true
    mode: 0644
