font_family             JetBrainsMono Nerd Font
font_size               14.0

scrollback_lines        100000

cursor_blink_interval   0
cursor_shape            beam

enable_audio_bell       no
confirm_os_window_close 0

# https://github.com/kovidgoyal/kitty/issues/1951
clipboard_control       write-clipboard write-primary no-append
hide_window_decorations yes

shell                   fish
shell_integration       no-cursor

include                 themes/Dracula.conf
background              #1a1b26
