- name: Set up user.gitconfig
  ansible.builtin.template:
    src: gitconfig.user
    dest: "{{ home }}/.gitconfig.user"
    mode: "0o644"

- name: Set up global .gitconfig
  ansible.builtin.file:
    src: "{{ role_host_path }}/files/gitconfig"
    dest: "{{ home }}/.gitconfig"
    state: link

- name: Install gitleaks completions
  ansible.builtin.shell: |
    {{ home }}/.local/bin/gitleaks completion bash > {{ home }}/.local/share/bash-completion/completions/gitleaks
    {{ home }}/.local/bin/gitleaks completion fish > {{ home }}/.config/fish/completions/gitleaks.fish
  args:
    executable: bash
  changed_when: false

- name: Set up .mrconfig
  ansible.builtin.file:
    src: "{{ role_host_path }}/files/mrconfig"
    dest: "{{ home }}/.mrconfig"
    state: link

- name: Download gh man
  ansible.builtin.unarchive:
    src: "{{ manifest.gh.url }}"
    dest: "{{ home }}/.local/share/"
    remote_src: true
    extra_opts:
      - --strip-components=2
      - --exclude=gh
    # See https://docs.ansible.com/ansible/latest/collections/ansible/builtin/unarchive_module.html#parameter-owner
    # If left unspecified and we are configuring for root user,
    # ansible will not set user and group for us,
    # which leads to incorrect ownership of the extracted files
    # and idempotency issues.
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  retries: "{{ web_retries }}"
  delay: "{{ web_delay }}"
  register: shell_utils_downloaded
  until: shell_utils_downloaded is not failed

- name: Create ~/.config/lazygit directory
  ansible.builtin.file:
    path: "{{ home }}/.config/lazygit"
    state: directory
    mode: "0o755"

# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
- name: Create symlink to global lazygit config
  ansible.builtin.file:
    src: "{{ role_host_path }}/files/lazygit.yaml"
    dest: "{{ home }}/.config/lazygit/config.yml"
    state: link

- name: Set up bash
  ansible.builtin.lineinfile:
    path: "{{ home }}/.bashrc"
    regexp: "source .*/{{ role_name }}/files"
    line: source {{ role_host_path }}/files/bash.sh

- name: Create symlinks to fish functions
  ansible.builtin.file:
    src: "{{ role_host_path }}/files/fish_functions/{{ item | basename }}"
    dest: "{{ home }}/.config/fish/functions/{{ item | basename }}"
    state: link
  loop: "{{ lookup('fileglob', '{{ role_path }}/files/fish_functions/*', wantlist=True) }}"
