- name: Install git
  become: true
  ansible.builtin.apt:
    name: git

- name: Set up global .gitconfig
  ansible.builtin.file:
    src: "{{ remote_role_path }}/files/gitconfig"
    dest: "{{ home }}/.gitconfig"
    state: link
    force: true

- name: Add git-secret gpg key
  become: true
  ansible.builtin.get_url:
    url: "{{ git_secret_gpg }}"
    dest: /etc/apt/trusted.gpg.d/git_secret.asc
  retries: "{{ web_retries }}"
  delay: "{{ web_delay }}"
  register: installed
  until: installed is not failed

- name: Add git-secret repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/git_secret.asc] {{ git_secret_repo }} git-secret main

- name: Install git secret
  become: true
  ansible.builtin.apt:
    name: git-secret

- name: Install mr
  become: true
  ansible.builtin.apt:
    name: mr

- name: Set up .mrconfig
  ansible.builtin.file:
    src: "{{ remote_role_path }}/files/mrconfig"
    dest: "{{ home }}/.mrconfig"
    state: link
    force: true

- name: Set up bash
  ansible.builtin.lineinfile:
    path: "{{ home }}/.bashrc"
    regexp: 'source .*/{{ role_name }}/files'
    line: source {{ remote_role_path }}/files/bash.sh

- name: Create symlinks to fish functions
  ansible.builtin.file:
    src: "{{ remote_role_path }}/files/fish_functions/{{ item | basename }}"
    dest: "{{ home }}/.config/fish/functions/{{ item | basename }}"
    state: link
    force: true
  loop: "{{ lookup('fileglob', '{{ role_path }}/files/fish_functions/*', wantlist=True) }}"
