- name: Add mattermost gpg key
  become: true
  ansible.builtin.get_url:
    url: "{{ mattermost_gpg }}"
    dest: "{{ apt_keys }}/mattermost.asc"
    mode: "0o644"

- name: Add mattermost repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by={{ apt_keys }}/mattermost.asc] {{ mattermost_repo }} stable main

# Using apt is preffered way, because it can be tested inside containers
- name: Install mattermost
  become: true
  ansible.builtin.apt:
    name:
      - mattermost-desktop
  when: ansible_distribution_version is version('23.04', '<=')

# However, mattermost-desktop is not installable via apt on Ubuntu 23.10
# because it uses deprecated gconf2 lib
# So we are using snap, which non-testable inside containers
- name: Install snap mattermost
  community.general.snap:
    name: mattermost-desktop
  when: false
