tick_rate = 200

[keybindings]
# ctrl-a = "go_to_input_start"
ctrl-b = "scroll_preview_half_page_up"
# ctrl-c = "quit"
ctrl-d = "select_next_half_page_nocycle"
# ctrl-e = "go_to_input_end"
ctrl-f = "scroll_preview_half_page_down"
# ctrl-g -- FREE.
# ctrl-h -- tmux navigation.
# ctrl-i -- shell reserved.
# ctrl-j -- tmux navigation.
# ctrl-k -- tmux navigation.
# ctrl-l -- tmux navigation.
# ctrl-m -- shell reserved.
# ctrl-n = "select_next_entry"
# ctrl-o = channel reserved.
# ctrl-p = "select_prev_entry"
# ctrl-q = channel reserved.
ctrl-r  = "cycle_sources"
# ctrl-s -- tmux reserved.
# ctrl-t = "toggle_remote_control"
ctrl-u = "select_prev_half_page_nocycle"
# ctrl-v -- channel reserved.
# ctrl-w = "delete_prev_word"
ctrl-x = "toggle_layout"
ctrl-y = "copy_entry_to_clipboard"
ctrl-z = "toggle_help"

[ui]
theme = "tokyonight"

[ui.theme_overrides]
result_name_fg = '#17d4ff'
selection_fg = '#21fc49'
remote_control_mode_bg = '#21fc49'

[ui.preview_panel]
scrollbar = false

[ui.status_bar]
hidden = true
