- name: Install Microsoft GPG keys
  become: true
  ansible.builtin.apt:
    deb: "{{ microsoft_gpg_deb }}"
  retries: "{{ web_retries }}"
  delay: "{{ web_delay }}"
  register: installed
  until: installed is not failed
  when: false # Fails

- name: Install powershell
  become: true
  ansible.builtin.apt:
    name: "powershell-lts={{ powershell_version }}"
  retries: "{{ web_retries }}"
  delay: "{{ web_delay }}"
  register: installed
  until: installed is not failed
  when: false # Fails

- name: Create Powershell config dir in Windows
  ansible.builtin.file:
    dest: "{{ windows_home }}/Documents/Powershell"
    state: directory
    mode: 0777
  when: in_wsl

# Powershell on Windows does not recognize symlinks
- name: Copy Profile.ps1 to Windows dir
  ansible.builtin.copy:
    src: "{{ role_path }}/files/Profile.ps1"
    dest: "{{ windows_home }}/Documents/Powershell/Profile.ps1"
    mode: 0777
  when: in_wsl
