# Connecting to hardware-keyed WiFi on NixOS through NetworkManager
# requires PKCS#11 engine paths to be set in wpa_supplicant's global
# configuration so that TLS authentication can use the TPM-backed
# smartcard module.
#
# === Problem ===
#
# wpa_supplicant configuration file supports pkcs11_engine_path and
# pkcs11_module_path parameters, which could be specified in
# file /etc/wpa_supplicant/nixos.conf (generated by networking.wireless
# .extraConfig).
# wpa_supplicant is started with -c /etc/wpa_supplicant/nixos.conf,
# but tls_init() receives null values for these paths — the config file
# is never read for any interface managed by NetworkManager.
#
# === Root Cause ===
#
# 1. The wpa_supplicant systemd service starts with "-u -c .../nixos.conf"
#    but NO -i flag. The -u flag enables D-Bus control; without -i,
#    wpa_supplicant skips interface creation and waits for D-Bus clients.
#
# 2. NetworkManager calls CreateInterface via D-Bus to add wlp0s20f3.
#    NM does NOT pass a ConfigFile argument (it manages per-connection
#    settings dynamically and has no concept of passing a static config).
#
# 3. In wpa_supplicant_add_iface(), when iface->confname is NULL,
#    wpa_config_alloc_empty() is called — an empty config with all
#    global settings (pkcs11 paths, bgscan, pmf, etc.) set to NULL.
#
# 4. When EAP-TLS auth starts, tls_init() receives this empty config,
#    so the PKCS#11 engine is never loaded.
#
# The config file /etc/wpa_supplicant/nixos.conf is never fopen()-ed
# by the process.
#
# === Alternatives Considered ===
#
# A. Hardcode PKCS#11 paths at build time via CONFIG_PKCS11_ENGINE_PATH /
#    CONFIG_PKCS11_MODULE_PATH macros in wpa_supplicant's .config.
#    Pros: no C source changes, shortest overlay.
#    Cons: paths are baked into the binary (brittle); config file parsing
#    for these options is compiled out; doesn't fix other silent losses
#    of global settings (bgscan, okc, sae_pwe, openssl_ciphers, etc.).
#
# B. Patch NetworkManager to pass ConfigFile in CreateInterface.
#    Pros: fixes the gap where it originates.
#    Cons: requires patching a separate package; NM upstream is unlikely
#    to accept such a change (global supplicant settings are outside
#    NM's connection-profile model).
#
# C. Patch wpa_supplicant to fall back to the startup config file when
#    interfaces are created via D-Bus without a ConfigFile argument.
#    Pros: generic fix for all global options (PKCS#11, bgscan, okc,
#    sae_pwe, openssl_ciphers, etc.) regardless of how the interface is
#    created; config file remains the single source of truth for global
#    settings; aligns with NM's orthogonal-layers model.
#    Cons: requires a non-trivial C source patch that must be maintained
#    across wpa_supplicant version upgrades.
#
# === Decision ===
#
# Hardcode PKCS#11 paths at build time (Alternative A).
# Solving local problem without accepting burden of patch maintenance.

{ inputs, ... }: final: prev: {
  wpa_supplicant = prev.wpa_supplicant.overrideAttrs (old: {
    extraConfig = old.extraConfig + ''
      CONFIG_PKCS11_ENGINE_PATH=/run/current-system/sw/lib/engines/pkcs11.so
      CONFIG_PKCS11_MODULE_PATH=/run/current-system/sw/lib/libtpm2_pkcs11.so
    '';
  });
  # libp11 also has another undebugged problem.
  # The only known thing is that this is a first problematic commit:
  # https://github.com/OpenSC/libp11/commit/60329e0502f751705bb939ad06574e36e4a42bc2
  libp11 = prev.libp11.overrideAttrs (old: {
    version = "0.4.13";
    src = final.fetchurl {
      url = "https://github.com/OpenSC/libp11/archive/libp11-0.4.13.tar.gz";
      hash = "sha256-BE2i20ZL/1SmcewpGqE7SGsEa0xtZwVrROd9lr5Q38Q=";
    };
  });
}
