- name: Install turbovnc on Ubuntu
  become: true
  ansible.builtin.apt:
    deb: "{{ manifest.turbovnc.url }}"
  retries: "{{ web_retries }}"
  delay: "{{ web_delay }}"
  register: turbovnc_installed
  until: turbovnc_installed is not failed
  when: ansible_distribution == 'Ubuntu'

- name: Install turbovnc on Fedora
  become: true
  ansible.builtin.dnf:
    name: "{{ manifest.turbovnc.url }}"
    disable_gpg_check: true
  retries: "{{ web_retries }}"
  delay: "{{ web_delay }}"
  register: turbovnc_installed
  until: turbovnc_installed is not failed
  when: ansible_distribution == 'Fedora'
