- name: Install go
  become: true
  ansible.builtin.package:
    name: "{{ {'Ubuntu': 'golang-go', 'Fedora': 'golang'}[ansible_distribution] }}"

- name: Set up bash
  ansible.builtin.lineinfile:
    path: "{{ home }}/.bashrc"
    regexp: "source .*/{{ role_name }}/files"
    line: source {{ remote_role_path }}/files/bash.sh

- name: Create symlink to fish config of {{ role_name }}
  ansible.builtin.file:
    src: "{{ remote_role_path }}/files/{{ role_name }}.fish"
    dest: "{{ home }}/.config/fish/conf.d/{{ role_name }}.fish"
    state: link
