# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  inputs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
    # It is actually Lenovo ThinkPad P15s Gen 2i, but there is no such config in nixos-hardware.
    # p14s-intel-gen2 looks very similar, at least it has matching PCI bus ids.
    # I.e. on the real machine `lspci` output:
    # $ lspci
    # 00:02.0 VGA compatible controller: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] (rev 01)
    # 01:00.0 3D controller: NVIDIA Corporation TU117GLM [Quadro T500 Mobile] (rev a1)
    # ...
    #
    # p14s-intel-gen2 config:
    # intelBusId = "PCI:0:2:0";
    # nvidiaBusId = "PCI:1:0:0";
    inputs.nixos-hardware.nixosModules.lenovo-thinkpad-p14s-intel-gen2
  ];

  boot = {
    initrd = {
      availableKernelModules = [
        "xhci_pci"
        "thunderbolt"
        "nvme"
        "usbhid"
        "usb_storage"
        "sd_mod"
        "rtsx_pci_sdmmc"
      ];
      kernelModules = [ ];
      luks.devices."luks-af224072-4e2b-4576-95c0-86df4fa2a40a".device =
        "/dev/disk/by-uuid/af224072-4e2b-4576-95c0-86df4fa2a40a";
    };

    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];
  };

  fileSystems."/" = {
    device = "/dev/mapper/luks-af224072-4e2b-4576-95c0-86df4fa2a40a";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/DADD-39D5";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
