- name: Install tmux packages
  become: true
  ansible.builtin.package:
    name:
      - tmux
      - python3-libtmux
  register: tmux_installed

- name: Create tmux config directory
  ansible.builtin.file:
    path: "{{ tmux_config_dir }}"
    state: directory
    mode: "0o755"

- name: Install tmux-plugin-manager
  ansible.builtin.git:
    repo: "{{ manifest.tpm.url }}"
    dest: "{{ tmux_tpm_dir }}"
    version: "{{ manifest.tpm.version }}"
  register: tmux_downloaded
  retries: "{{ web_retries }}"
  delay: "{{ web_delay }}"
  until: tmux_downloaded is not failed

- name: Set up bash
  ansible.builtin.lineinfile:
    path: "{{ home }}/.bashrc"
    regexp: "source .*/{{ role_name }}/files"
    line: source {{ role_host_path }}/files/bash.sh
  # Disable automatic tmux open for bash
  when: false

- name: Create symlink to fish config of {{ role_name }}
  ansible.builtin.file:
    src: "{{ role_host_path }}/files/{{ role_name }}.fish"
    dest: "{{ home }}/.config/fish/conf.d/{{ role_name }}.fish"
    state: link

- name: Create symlink to tmux.conf
  ansible.builtin.file:
    src: "{{ role_host_path }}/files/tmux.conf"
    dest: "{{ tmux_config }}"
    state: link

- name: Reload tmux config
  ansible.builtin.shell: |
    {{ tmux_tpm_dir }}/bin/install_plugins
    {{ tmux_tpm_dir }}/bin/update_plugins all
    tmux -c 'tmux source-file "{{ tmux_config }}"'
  args:
    executable: bash
  changed_when: tmux_installed is changed
