- name: Check sanity
  ansible.builtin.assert:
    that:
      - ansible_distribution in "Ubuntu|Fedora"

- name: Install common utils for other Ansible tasks
  become: true
  ansible.builtin.package:
    name:
      - curl
      - gnupg
      - patch
      - rsync
      - tzdata
      - unzip
      - "{{ {'Ubuntu': 'xz-utils', 'Fedora': 'xz'}[ansible_distribution] }}"

- name: Install Ubuntu-specific common utils for other Ansible tasks
  become: true
  ansible.builtin.apt:
    name:
      - gpg-agent
      - locales
      - ntpdate
      - software-properties-common
  when: ansible_distribution == "Ubuntu"

- name: Install hwclock for Ubuntu >= 23.10
  become: true
  ansible.builtin.package:
    name:
      - util-linux-extra
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version is version('23.10', '>=')

- name: Install Fedora-specific common utils for other Ansible tasks
  become: true
  ansible.builtin.dnf:
    name:
      - dnf-command(config-manager)
      - dnf-plugins-core
      - util-linux
  when: ansible_distribution == "Fedora"

- name: Set locale
  become: true
  community.general.locale_gen:
    name: "{{ profile.locale }}"
  # TODO: enable locale on Fedora
  when: ansible_distribution == "Ubuntu"

- name: Set timezone
  become: true
  community.general.timezone:
    name: "{{ profile.timezone }}"

- name: Get user id
  ansible.builtin.getent:
    database: passwd
    key: "{{ ansible_user }}"

- name: Check if inside container
  ansible.builtin.shell: ([[ -f /.dockerenv || -f /run/.containerenv ]]) && echo true || echo false
  args:
    executable: bash
  changed_when: false
  register: basic_utils_container_out

- name: Check if inside WSL
  ansible.builtin.shell: |
    set -o pipefail
    kernel_is_wsl=$(uname --all | grep --quiet WSL && echo true || echo false)
    has_wsl_interop=$([[ -n "$WSL_INTEROP" ]] && echo true || echo false)
    c_is_mounted=$(ls /mnt/c &> /dev/null && echo true || echo false)
    if [[
        "$kernel_is_wsl" == "true" &&
        "$has_wsl_interop" == "true" &&
        "$c_is_mounted" == "true" &&
        : ]]; then
      echo true
    else
      echo false
    fi
  args:
    executable: bash
  changed_when: false
  register: basic_utils_wsl

- name: Check if gui installed
  ansible.builtin.find:
    paths: /usr/share/xsessions/
  register: basic_utils_x_list

- name: Set common facts
  ansible.builtin.set_fact:
    home: "{{ getent_passwd[ansible_user].4 }}"
    user_id: "{{ getent_passwd[ansible_user].1 }}"
    trusted: "{{ hostvars[inventory_hostname]['trusted'] }}"
    in_container: "{{ basic_utils_container_out.stdout }}"
    in_wsl: "{{ basic_utils_wsl.stdout }}"
    use_gui: "{{ basic_utils_x_list.files | length > 0 }}"

    web_delay: 30
    web_retries: 5
  tags:
    - skip_ansible_lint

- name: Print detected facts
  ansible.builtin.debug:
    msg:
      - "home: {{ home }}"
      - "trusted: {{ trusted }}"
      - "ansible_architecture: {{ ansible_architecture }}"
      - "deb_arch: {{ deb_arch }}"
      - "in_container: {{ in_container }}"
      - "in_wsl: {{ in_wsl }}"
      - "use_gui: {{ use_gui }}"
      - "user: {{ ansible_user }}"
      - "user_id: {{ user_id }}"

- name: Set correct state for directory /run/user/{{ user_id }}
  become: true
  ansible.builtin.file:
    path: "/run/user/{{ user_id }}/"
    state: directory
    mode: "0o700"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: WSL stuff
  when: in_wsl
  block:
    - name: Install WSL utils
      become: true
      ansible.builtin.package:
        name: wslu

    - name: Gather WSL facts
      ansible.builtin.shell: |
        wslpath $(wslvar USERPROFILE)
      args:
        executable: bash
      changed_when: false
      register: basic_utils_win_home

    - name: Set WSL facts
      ansible.builtin.set_fact:
        windows_home: "{{ basic_utils_win_home.stdout }}"
      tags:
        - skip_ansible_lint

    - name: Setup wsl.conf
      become: true
      ansible.builtin.copy:
        src: "{{ role_path }}/files/wsl.conf"
        dest: /etc/wsl.conf
        mode: "0o644"
      when: in_wsl
