- name: Check sanity
  ansible.builtin.assert:
    that:
      - user == ansible_user
      - ansible_os_family == "Debian"

- name: Install aptitude
  become: true
  ansible.builtin.apt:
    name:
      - aptitude

- name: Install common utils for other Ansible tasks
  become: true
  ansible.builtin.apt:
    name:
      - curl
      - gnupg
      - gpg-agent
      - locales
      - ntpdate
      - rsync
      - software-properties-common
      - tzdata
      - unzip
      - xz-utils

- name: Install hwclock for Ubuntu >= 23.10
  become: true
  ansible.builtin.apt:
    name:
      - util-linux-extra
  when: ansible_distribution_version is version('23.10', '>=')

- name: Set locale
  become: true
  community.general.locale_gen:
    name: en_US.UTF-8

- name: Set timezone
  become: true
  community.general.timezone:
    name: Europe/Moscow

- name: Check if inside WSL
  ansible.builtin.shell: |
    set -o pipefail
    kernel_is_wsl=$(uname --all | grep --quiet WSL && echo true || echo false)
    has_wsl_interop=$([[ -n "$WSL_INTEROP" ]] && echo true || echo false)
    c_is_mounted=$(ls /mnt/c &> /dev/null && echo true || echo false)
    if [[
        "$kernel_is_wsl" == "true" &&
        "$has_wsl_interop" == "true" &&
        "$c_is_mounted" == "true" &&
        : ]]; then
      echo true
    else
      echo false
    fi
  args:
    executable: bash
  changed_when: false
  register: basic_utils_wsl

- name: Check if inside container
  ansible.builtin.shell: ([[ -f /.dockerenv || -f /run/.containerenv ]]) && echo true || echo false
  args:
    executable: bash
  changed_when: false
  register: basic_utils_container

- name: Check if gui installed
  ansible.builtin.find:
    paths: /usr/share/xsessions/
  register: basic_utils_x_list

- name: Set common facts
  ansible.builtin.set_fact:
    in_container: "{{ basic_utils_container.stdout }}"
    in_wsl: "{{ basic_utils_wsl.stdout }}"
    use_gui: "{{ basic_utils_x_list.files | length > 0 }}"
  tags:
    - skip_ansible_lint

- name: Print detected facts
  ansible.builtin.debug:
    msg:
      - "home: {{ home }}"
      - "trusted: {{ trusted }}"
      - "in_container: {{ in_container }}"
      - "in_wsl: {{ in_wsl }}"
      - "use_gui: {{ use_gui }}"

- name: WSL stuff
  when: in_wsl
  block:
    - name: Install WSL utils
      become: true
      ansible.builtin.apt:
        name: wslu

    - name: Gather WSL facts
      ansible.builtin.shell: |
        wslpath $(wslvar USERPROFILE)
      args:
        executable: bash
      changed_when: false
      register: basic_utils_win_home

    - name: Set WSL facts
      ansible.builtin.set_fact:
        windows_home: "{{ basic_utils_win_home.stdout }}"
      tags:
        - skip_ansible_lint

    - name: Sync time
      become: true
      ansible.builtin.command: ntpdate ntp.ubuntu.com
      changed_when: false

    - name: Setup wsl.conf
      become: true
      ansible.builtin.copy:
        src: "{{ role_path }}/files/wsl.conf"
        dest: /etc/wsl.conf
        mode: "0o644"
      when: in_wsl
