credentials_path: "{{ dotfiles_path }}/roles/secrets/files/credentials.json"
gpg_key_dir: "private.gpg"
gpg_key_local_path: "{{ playbook_dir }}/{{ gpg_key_dir }}"
gpg_key_path: "{{ dotfiles_path }}/{{ gpg_key_dir }}"
ssh_dir: "roles/secrets/files/ssh"
ssh_local_path: "{{ playbook_dir }}/{{ ssh_dir }}"
ssh_path: "{{ dotfiles_path }}/{{ ssh_dir }}"
vpn_path: "{{ dotfiles_path }}/roles/secrets/files/vpn"
