- name: Create ~/.ssh directory
  ansible.builtin.file:
    path: "{{ home }}/.ssh"
    state: directory
    mode: "0o755"

- name: List decrypted private keys
  ansible.builtin.find:
    paths: "{{ ssh_client_host_path }}"
    patterns: "*rsa"
  register: ssh_rsa_keys

- name: Create symlinks to ssh private keys
  ansible.builtin.file:
    src: "{{ item.path }}"
    dest: "{{ home }}/.ssh/{{ item.path | basename }}"
    state: link
  loop: "{{ ssh_rsa_keys.files }}"
  loop_control:
    label: "{{ item.path | basename }}"

- name: List public keys
  ansible.builtin.find:
    paths: "{{ ssh_client_host_path }}"
    patterns: "*rsa.pub"
  register: ssh_rsa_pub_keys

- name: Create symlinks to ssh public keys
  ansible.builtin.file:
    src: "{{ item.path }}"
    dest: "{{ home }}/.ssh/{{ item.path | basename }}"
    state: link
  loop: "{{ ssh_rsa_pub_keys.files }}"
  loop_control:
    label: "{{ item.path | basename }}"

- name: Create symlink to fish config of {{ role_name }}
  ansible.builtin.file:
    src: "{{ role_host_path }}/files/{{ role_name }}.fish"
    dest: "{{ home }}/.config/fish/conf.d/{{ role_name }}.fish"
    state: link
