- name: Install ssh tools
  become: true
  ansible.builtin.package:
    name:
      - "{{ {'Ubuntu': 'libssl-dev', 'Fedora': 'openssl-devel'}[ansible_distribution] }}"
      - "{{ {'Ubuntu': 'openssh-client', 'Fedora': 'openssh'}[ansible_distribution] }}"
      - sshpass

- name: Create ~/.ssh directory
  ansible.builtin.file:
    path: "{{ home }}/.ssh"
    state: directory
    mode: "0o755"

- name: List ssh keys
  ansible.builtin.find:
    paths: "{{ ssh_client_host_path }}"
    patterns: ["*.sops", "*.pub"]
  register: ssh_rsa_keys

- name: Create symlinks to ssh keys
  ansible.builtin.file:
    src: "{{ item.path }}"
    dest: "{{ home }}/.ssh/{{ item.path | basename }}"
    state: link
  loop: "{{ ssh_rsa_keys.files }}"
  loop_control:
    label: "{{ item.path | basename }}"

- name: Create symlink to fish config of {{ role_name }}
  ansible.builtin.file:
    src: "{{ role_host_path }}/files/{{ role_name }}.fish"
    dest: "{{ home }}/.config/fish/conf.d/{{ role_name }}.fish"
    state: link
