- name: Install common utils
  become: true
  ansible.builtin.apt:
    name:
      - acpi
      - apt-transport-https
      - build-essential
      - bzip2
      - ca-certificates
      - dos2unix
      - file
      - flameshot
      - graphviz
      - gzip
      - htop
      - iptables
      - iputils-ping
      - lftp
      - libevent-dev
      - linux-tools-common
      - locales
      - lsb-release
      - ncurses-dev
      - net-tools
      - p7zip-full
      - p7zip-rar
      - pkg-config
      - tar
      - tcl
      - wget
      - zip

- name: Create ~/.config/yamlfmt directory
  ansible.builtin.file:
    path: "{{ home }}/.config/yamlfmt"
    state: directory
    mode: "0o755"

# https://github.com/google/yamlfmt#configuration-file
- name: Create symlink to global yamlfmt config
  ansible.builtin.file:
    src: "{{ remote_role_path }}/files/yamlfmt.yaml"
    dest: "{{ home }}/.config/yamlfmt/.yamlfmt"
    state: link

- name: Create ~/.config/yamllint directory
  ansible.builtin.file:
    path: "{{ home }}/.config/yamllint"
    state: directory
    mode: "0o755"

# https://yamllint.readthedocs.io/en/stable/configuration.html#configuration
- name: Create symlink to global yamllint config
  ansible.builtin.file:
    src: "{{ remote_role_path }}/files/yamllint.yaml"
    dest: "{{ home }}/.config/yamllint/config"
    state: link

# https://github.com/DavidAnson/markdownlint
- name: Create symlink to global markdownlint config
  ansible.builtin.file:
    src: "{{ remote_role_path }}/files/markdownlint.yaml"
    dest: "{{ home }}/.markdownlint.yaml"
    state: link

# https://github.com/nvuillam/npm-groovy-lint/blob/main/lib/.groovylintrc-recommended.json
- name: Create symlink to global groovylintrc config
  ansible.builtin.file:
    src: "{{ remote_role_path }}/files/groovylintrc.json"
    dest: "{{ home }}/.groovylintrc.json"
    state: link

- name: Create symlink to global yamllint config
  ansible.builtin.file:
    src: "{{ remote_role_path }}/files/yamllint.yaml"
    dest: "{{ home }}/.config/yamllint/config"
    state: link

- name: Create ~/.config/flameshot directory
  ansible.builtin.file:
    path: "{{ home }}/.config/flameshot"
    state: directory
    mode: "0o755"

- name: Create symlink to flameshot config
  ansible.builtin.file:
    src: "{{ remote_role_path }}/files/flameshot.ini"
    dest: "{{ home }}/.config/flameshot/flameshot.ini"
    state: link
    force: true
