- name: Install common utils
  become: true
  ansible.builtin.package:
    name:
      - "{{ {'Ubuntu': 'iputils-ping', 'Fedora': 'iputils'}[ansible_distribution] }}"
      - "{{ {'Ubuntu': 'libevent-dev', 'Fedora': 'libevent-devel'}[ansible_distribution] }}"
      - "{{ {'Ubuntu': 'ncurses-dev', 'Fedora': 'ncurses-devel'}[ansible_distribution] }}"
      - "{{ {'Ubuntu': 'p7zip-full', 'Fedora': 'p7zip'}[ansible_distribution] }}"
      - "{{ {'Ubuntu': 'p7zip-rar', 'Fedora': 'p7zip-plugins'}[ansible_distribution] }}"
      - acpi
      - apt-transport-https
      - bzip2
      - ca-certificates
      - dos2unix
      - file
      - flameshot
      - graphviz
      - gzip
      - htop
      - iptables
      - lftp
      - lsb-release
      - net-tools
      - pkg-config
      - tar
      - tcl
      - unar
      - unrar
      - wget
      - zip

- name: Setup printscreen shutter sound
  vars:
    common_utils_shutter: /usr/share/sounds/freedesktop/stereo/camera-shutter.oga
    common_utils_shutter_bak: /usr/share/sounds/freedesktop/stereo/camera-shutter.oga.bak
  block:
    - name: Check if shutter sound file exists
      ansible.builtin.stat:
        path: "{{ common_utils_shutter }}"
      register: common_utils_shutter_file

    - name: Copy shutter sound file to backup location
      become: true
      ansible.builtin.copy:
        src: "{{ common_utils_shutter }}"
        dest: "{{ common_utils_shutter_bak }}"
        mode: "0o644"
      when: common_utils_shutter_file.stat.exists

    - name: Delete shutter sound file
      become: true
      ansible.builtin.file:
        path: "{{ common_utils_shutter }}"
        state: absent

- name: Create ~/.config/yamlfmt directory
  ansible.builtin.file:
    path: "{{ home }}/.config/yamlfmt"
    state: directory
    mode: "0o755"

# https://github.com/google/yamlfmt#configuration-file
- name: Create symlink to global yamlfmt config
  ansible.builtin.file:
    src: "{{ role_host_path }}/files/yamlfmt.yaml"
    dest: "{{ home }}/.config/yamlfmt/.yamlfmt"
    state: link

- name: Create ~/.config/yamllint directory
  ansible.builtin.file:
    path: "{{ home }}/.config/yamllint"
    state: directory
    mode: "0o755"

# https://yamllint.readthedocs.io/en/stable/configuration.html#configuration
- name: Create symlink to global yamllint config
  ansible.builtin.file:
    src: "{{ role_host_path }}/files/yamllint.yaml"
    dest: "{{ home }}/.config/yamllint/config"
    state: link

# https://github.com/DavidAnson/markdownlint
- name: Create symlink to global markdownlint config
  ansible.builtin.file:
    src: "{{ role_host_path }}/files/markdownlint.yaml"
    dest: "{{ home }}/.markdownlint.yaml"
    state: link

# https://github.com/nvuillam/npm-groovy-lint/blob/main/lib/.groovylintrc-recommended.json
- name: Create symlink to global groovylintrc config
  ansible.builtin.file:
    src: "{{ role_host_path }}/files/groovylintrc.json"
    dest: "{{ home }}/.groovylintrc.json"
    state: link

- name: Create symlink to global yamllint config
  ansible.builtin.file:
    src: "{{ role_host_path }}/files/yamllint.yaml"
    dest: "{{ home }}/.config/yamllint/config"
    state: link

- name: Create ~/.config/flameshot directory
  ansible.builtin.file:
    path: "{{ home }}/.config/flameshot"
    state: directory
    mode: "0o755"

- name: Create symlink to flameshot config
  ansible.builtin.file:
    src: "{{ role_host_path }}/files/flameshot.ini"
    dest: "{{ home }}/.config/flameshot/flameshot.ini"
    state: link
    force: true
