#!/usr/bin/env bash

changed=$(git diff --cached --name-only)
regex="(\
rsa|\
ed25519|\
ed25519_sk|\
ecdsa|\
ecdsa_sk|\
ovpn|\
auth|\
amnezia|\
xray|\
socks|\
credentials.json|\
private.gpg\
)\$"

secrets=$(echo "$changed" | grep --perl-regex "$regex")
if [[ -n "$secrets" ]]; then
  echo "Refusing to commit potentially sensitive info. Detected files:"
  echo "$secrets"
  exit 1
fi
