- name: Install perl
  become: true
  ansible.builtin.apt:
    name:
      - perl
      - perl-doc
      - cpanminus

- name: Configure cpan
  become: true
  ansible.builtin.shell: |
    set -o pipefail
    echo y | cpan
  args:
    executable: bash
  register: perl_log
  changed_when: ("configure as much as possible automatically" in perl_log)

- name: Install common perl packages
  become: true
  community.general.cpanm:
    name: "{{ item }}"
  loop:
    - Archive::Tar
    - File::Basename
    - File::Find
    - File::HomeDir
    - Graph::Easy
    - Log::Dispatch::File
    - Log::Log4perl
    - Unicode::GCString
    - YAML::Tiny
