- name: Create writable nix directory
  become: true
  ansible.builtin.file:
    path: "/nix"
    state: directory
    mode: "0o755"
    # Normally, all actions performed by this projects do not make any
    # special case inside system settings for the target user.
    # However, nix installation is an exception due to its complexity.
    # User-agnostic (multi-user) installation does not work on Fedora, since it does not support
    # SELinux at the moment.
    # Also it is very intrusive and creates daemons, service users and groups etc.
    # On contrary, single-user installation is much simpler, but favors target user
    # in system-wide /nix/store directory.
    group: "{{ ansible_user }}"
    owner: "{{ ansible_user }}"

- name: Install nix
  ansible.builtin.shell: |
    sh <(curl -L https://releases.nixos.org/nix/nix-2.28.3/install) --no-daemon --yes
  args:
    creates: "/nix/store"
    executable: bash
  # nix installation script does not support installing as root
  # This is normally not a problem, but there is one CI check which must be run as root
  # (Since it is really hard to setup VM Github Action to run as non-root)
  when: ansible_user != "root"

- name: Download nixfmt
  ansible.builtin.get_url:
    url: "{{ manifest.nixfmt.url }}"
    dest: "{{ home }}/.local/bin/nixfmt"
    mode: "0o755"
  retries: "{{ web_retries }}"
  delay: "{{ web_delay }}"
  register: nixfmt_downloaded
  until: nixfmt_downloaded is not failed
