- name: Set WSL clipboard
  when: in_wsl
  block:
    - name: Create symlink to clip.exe
      become: true
      ansible.builtin.file:
        src: /mnt/c/Windows/System32/clip.exe
        dest: "{{ home }}/.local/bin/clip.exe"
        state: link

    - name: Create dir for win32yank
      become: true
      ansible.builtin.file:
        dest: "{{ clipboard_win32yank_dir }}"
        state: directory
        mode: "0o777"

    - name: Download win32yank.exe
      ansible.builtin.unarchive:
        src: "{{ manifest.clipboard.url }}"
        dest: "{{ clipboard_win32yank_dir }}"
        remote_src: true
        creates: "{{ clipboard_win32yank_dir }}/win32yank.exe"
      retries: "{{ web_retries }}"
      delay: "{{ web_delay }}"
      register: clipboard_downloaded
      until: clipboard_downloaded is not failed

    - name: Create symlink to win32yank.exe
      become: true
      ansible.builtin.file:
        src: "{{ clipboard_win32yank_dir }}/win32yank.exe"
        dest: "{{ home }}/.local/bin/win32yank.exe"
        state: link

    - name: Remove xsel package if in WSL
      become: true
      ansible.builtin.apt:
        name: xsel
        state: absent

    - name: Set clipboard fact to win32yank
      ansible.builtin.set_fact:
        clipboard: win32yank
      tags:
        - skip_ansible_lint

- name: Set xsel clipboard
  when: not in_wsl
  block:
    - name: Set clipboard when not in WSL
      become: true
      ansible.builtin.apt:
        name: xsel

    - name: Set clipboard fact to xsel
      ansible.builtin.set_fact:
        clipboard: xsel
      tags:
        - skip_ansible_lint
