[[mgr.prepend_keymap]]
on = ["?"]
run = "help"
desc = "Show help"

[[mgr.prepend_keymap]]
on = ["<C-n>"]
run = "arrow 1"
desc = "Next item"

[[mgr.prepend_keymap]]
on = ["<C-p>"]
run = "arrow -1"
desc = "Prev item"

[[mgr.prepend_keymap]]
on = ["<C-d>"]
run = "arrow 20"
desc = "Scroll file list down"

[[mgr.prepend_keymap]]
on = ["<C-u>"]
run = "arrow -20"
desc = "Scroll file list up"

[[mgr.prepend_keymap]]
on = ["<C-f>"]
run = "seek 10"
desc = "Scroll content down"

[[mgr.prepend_keymap]]
on = ["<C-b>"]
run = "seek -10"
desc = "Scroll content up"
