[tool.pylint]
max-line-length = 120
disable = [
  "logging-fstring-interpolation",
  "logging-not-lazy",
  "missing-docstring",
  "too-few-public-methods",
  "too-many-arguments",
  "too-many-branches",
  "too-many-instance-attributes",
]
