line-length = 120

[lint]
select = ["ALL"]

ignore = [
  # warning: `one-blank-line-before-class` (D203) and
  #          `no-blank-line-before-class`  (D211) are incompatible.
  #          Ignoring `one-blank-line-before-class`.
  "D203",
  # warning: `multi-line-summary-first-line`  (D212) and
  #          `multi-line-summary-second-line` (D213) are incompatible.
  #          Ignoring `multi-line-summary-second-line`.
  "D213",
  # "Missing docstring"
  "D100",
  "D101",
  "D102",
  "D103",
  "D104",
  "D107",
  # "Logging statement uses f-string"
  # I personally don't find performance concerns reasonable enough.
  "G004",
  # "Prefer absolute imports over relative imports from parent modules"
  "TID252",
  # "Avoid specifying long messages outside the exception class"
  "TRY003",
  # "Consider moving this statement to an `else` block"
  # I find `try-except-else` more confusing than this rule suggests.
  "TRY300",

  # "Missing `from __future__ import annotations`, but uses PEP 604 union"
  "FA102",

  # warning: The following rules may cause conflicts when used with the formatter: `COM812`, `ISC001`.
  # COM812: Checks for the absence of trailing commas.
  # ISC001: Checks for implicitly concatenated strings on a single line.
  "COM812",
  "ISC001",
]
