- name: Install TeX Live
  become: true
  ansible.builtin.apt:
    name: texlive-full
  retries: 3
  register: texlive_installed
  until: texlive_installed is not failed

- name: Install perl packages
  become: true
  community.general.cpanm:
    name: "{{ item }}"
  loop:
    - File::HomeDir
    - Log::Dispatch::File
    - Unicode::GCString
    - YAML::Tiny

- name: Install support packages
  become: true
  ansible.builtin.apt:
    name:
      - bibclean
      - libasound2
      - msttcorefonts
      - poppler-utils
      - python3-pygments
      - ttf-mscorefonts-installer
      - xvfb

- name: Install draw.io
  become: true
  ansible.builtin.apt:
    deb: "{{ drawio_url }}"
  retries: "{{ web_retries }}"
  delay: "{{ web_delay }}"
  register: installed
  until: installed is not failed
