- name: Install TeX Live
  become: true
  ansible.builtin.package:
    name: "{{ {'Ubuntu': 'texlive-full', 'Fedora': 'texlive-scheme-full'}[ansible_distribution] }}"
  retries: 3
  register: latex_installed
  until: latex_installed is not failed

- name: Install support packages
  become: true
  ansible.builtin.package:
    name:
      - poppler-data
      - poppler-utils
      - python3-pygments
      - python3-sympy
      - "{{ {'Ubuntu': 'msttcorefonts', 'Fedora': 'mscore-fonts-all'}[ansible_distribution] }}"
      - "{{ {'Ubuntu': 'ttf-mscorefonts-installer', 'Fedora': 'mscore-fonts-all'}[ansible_distribution] }}"
      - "{{ {'Ubuntu': 'xvfb', 'Fedora': 'xorg-x11-server-Xvfb'}[ansible_distribution] }}"

- name: Install libasound2 (for Ubuntu < 24.04)
  become: true
  ansible.builtin.apt:
    name: libasound2
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version is version('24.04', '<')

# Weirdly, liboss4-salsa-asound2 alternative is automatically uninstalled by
# java openjdk-21-jdk package, thus choosing libasound2t64 instead
- name: Install libasound2t64 (for Ubuntu >= 24.04)
  become: true
  ansible.builtin.apt:
    name: libasound2t64
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version is version('24.04', '>=')

- name: Install draw.io on Ubuntu
  become: true
  ansible.builtin.apt:
    deb: "{{ manifest.drawio.url }}"
  retries: "{{ web_retries }}"
  delay: "{{ web_delay }}"
  register: latex_installed
  until: latex_installed is not failed
  when: ansible_distribution == 'Ubuntu' and false

- name: Install draw.io on Fedora
  become: true
  ansible.builtin.dnf:
    name: "{{ manifest.drawio.url }}"
    disable_gpg_check: true
  retries: "{{ web_retries }}"
  delay: "{{ web_delay }}"
  register: latex_installed
  until: latex_installed is not failed
  when: ansible_distribution == 'Fedora' and false
