- name: Install TeX Live
  become: true
  ansible.builtin.apt:
    name: texlive-full
  retries: 3
  register: latex_installed
  until: latex_installed is not failed

- name: Install support packages
  become: true
  ansible.builtin.apt:
    name:
      - bibclean
      - libasound2
      - msttcorefonts
      - poppler-utils
      - python3-pygments
      - ttf-mscorefonts-installer
      - xvfb

- name: Install draw.io
  become: true
  ansible.builtin.apt:
    deb: "{{ manifest.drawio.url }}"
  retries: "{{ web_retries }}"
  delay: "{{ web_delay }}"
  register: latex_installed
  until: latex_installed is not failed
