#!/usr/bin/env bash

changed=$(git diff --cached --name-only)
regex="(\
rsa|\
pub|\
ovpn|\
auth|\
amnezia|\
xray|\
socks|\
credentials.json|\
ssh_server_config.yaml|\
private.gpg\
)\$"

secrets=$(echo "$changed" | grep --perl-regex "$regex")
if [[ -n "$secrets" ]]; then
  echo "Refusing to commit potentially sensitive info. Detected files:"
  echo "$secrets"
  exit 1
fi
