- name: Configure terminals
  when: not in_wsl
  block:
    # TODO: Change it to normal apt when at least 0.23 is available
    - name: Install kitty
      ansible.builtin.unarchive:
        src: "{{ manifest.kitty.url }}"
        dest: "{{ home }}/.local/kitty.app"
        remote_src: true
      retries: "{{ web_retries }}"
      delay: "{{ web_delay }}"
      register: kitty
      until: kitty is not failed
    - name: Create kitty symlinks
      ansible.builtin.file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
        force: true
      loop:
        - {src: "{{ home }}/.local/kitty.app/bin/kitty", dest: "{{ home }}/.local/bin/kitty"}
        - {src: "{{ home }}/.local/kitty.app/bin/kitten", dest: "{{ home }}/.local/bin/kitten"}
    - name: Copy kitty desktop files
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        remote_src: true
        mode: 0644
      changed_when: kitty is changed
      loop:
        # yamllint disable-line rule:line-length
        - {src: "{{ home }}/.local/kitty.app/share/applications/kitty.desktop", dest: "{{ home }}/.local/share/applications/kitty.desktop"}
        # yamllint disable-line rule:line-length
        - {src: "{{ home }}/.local/kitty.app/share/applications/kitty-open.desktop", dest: "{{ home }}/.local/share/applications/kitty-open.desktop"}
    - name: Update icon paths in kitty desktop files
      ansible.builtin.lineinfile:
        path: "{{ item }}"
        regexp: '^Icon='
        line: Icon={{ home }}/.local/kitty.app/share/icons/hicolor/256x256/apps/kitty.png
      changed_when: kitty is changed
      loop:
        - "{{ home }}/.local/share/applications/kitty.desktop"
        - "{{ home }}/.local/share/applications/kitty-open.desktop"
    - name: Update exec paths in kitty desktop files
      ansible.builtin.lineinfile:
        path: "{{ item }}"
        regexp: '^Exec='
        line: Exec={{ home }}/.local/kitty.app/bin/kitty
      changed_when: kitty is changed
      loop:
        - "{{ home }}/.local/share/applications/kitty.desktop"
        - "{{ home }}/.local/share/applications/kitty-open.desktop"

    - name: Create ~/.config/kitty/ directory
      ansible.builtin.file:
        dest: "{{ home }}/.config/kitty"
        state: directory
        mode: 0755

    - name: Create symlink to kitty config
      ansible.builtin.file:
        src: "{{ remote_role_path }}/files/kitty.conf"
        dest: "{{ home }}/.config/kitty/kitty.conf"
        state: link
        force: true

    - name: Install WezTerm
      # Actually is laggy on my machine
      become: true
      ansible.builtin.apt:
        deb: "{{ manifest.wezterm.url }}"
      retries: "{{ web_retries }}"
      delay: "{{ web_delay }}"
      register: installed
      until: installed is not failed

    - name: Create symlink to wezterm config
      ansible.builtin.file:
        src: "{{ remote_role_path }}/files/wezterm.lua"
        dest: "{{ home }}/.wezterm.lua"
        state: link
        force: true

    - name: Create ~/.config/tilda/ directory
      ansible.builtin.file:
        dest: "{{ home }}/.config/tilda"
        state: directory
        mode: 0755

    - name: Create symlink to tilda config
      ansible.builtin.file:
        src: "{{ remote_role_path }}/files/tilda.conf"
        dest: "{{ home }}/.config/tilda/config_0"
        state: link
        force: true

    - name: Create ~/.local/share/konsole/ directory
      ansible.builtin.file:
        dest: "{{ home }}/.local/share/konsole"
        state: directory
        mode: 0755

    - name: Create symlink to konsole profile
      ansible.builtin.file:
        src: "{{ remote_role_path }}/files/konsole.profile"
        dest: "{{ home }}/.local/share/konsole/Main.profile"
        state: link
        force: true

    - name: Init ~/.config.konsolerc
      ansible.builtin.lineinfile:
        create: true
        path: "{{ home }}/.config/konsolerc"
        regexp: '\[Desktop Entry\]'
        line: "[Desktop Entry]"
        insertbefore: BOF
        mode: 0644

    - name: Set konsole default profile
      ansible.builtin.lineinfile:
        path: "{{ home }}/.config/konsolerc"
        regexp: 'DefaultProfile='
        line: DefaultProfile=Main.profile
        insertafter: '\[Desktop Entry\]'
