- name: Create symlink to proxied nvim binary
  ansible.builtin.file:
    src: "{{ role_host_path }}/files/nvim-proxied.sh"
    dest: "{{ home }}/.local/bin/nvim"
    state: link

- name: Install vim as a backup
  become: true
  ansible.builtin.package:
    name: vim

- name: Install neovim gem
  become: true
  community.general.gem:
    name: neovim
  when: ansible_distribution == "Ubuntu" or
    (ansible_distribution == "Fedora" and ansible_distribution_version is version('40', '>='))

- name: Install node.js packages
  become: true
  community.general.npm:
    name: "{{ item }}"
    global: true
  when: false # broken
  loop:
    - neovim
    - npm-groovy-lint

- name: Install perl neovim package
  become: true
  community.general.cpanm:
    name: Neovim::Ext
  # TODO: enable this
  when: false

- name: Install LazyVim
  block:
    - name: Install lazy.nvim
      ansible.builtin.git:
        repo: "https://github.com/folke/lazy.nvim"
        dest: "{{ neovim_base }}_3/share/lazy/lazy.nvim"
        version: "{{ neovim_lazy_lock['lazy.nvim'].commit }}"
        force: true
      vars:
        neovim_lazy_lock: "{{ lookup('file', 'lazy/lazy-lock.json') | from_json }}"
      register: neovim_lazy
      retries: "{{ web_retries }}"
      delay: "{{ web_delay }}"
      until: neovim_lazy is not failed
      changed_when: neovim_lazy.before != neovim_lazy.after

    - name: Create config directory for lazy
      ansible.builtin.file:
        path: "{{ neovim_base }}_3"
        state: directory
        mode: "0o755"

    - name: Create symlink to LazyVim config
      ansible.builtin.file:
        src: "{{ role_host_path }}/files/lazy"
        dest: "{{ neovim_base }}_3/config"
        state: link
        force: true

    - name: Set up clipboard for neovim
      ansible.builtin.template:
        src: this_clipboard.lua
        dest: "{{ neovim_base }}_3/config/lua/config/this_clipboard.lua"
        mode: "0o644"

- name: Install LazyVim experiments
  block:
    - name: Install lazy.nvim
      ansible.builtin.git:
        repo: "https://github.com/folke/lazy.nvim"
        dest: "{{ neovim_base }}_4/share/lazy/lazy.nvim"
        version: "{{ neovim_lazy_lock['lazy.nvim'].commit }}"
        force: true
      vars:
        neovim_lazy_lock: "{{ lookup('file', 'lazy/lazy-lock.json') | from_json }}"
      register: neovim_lazy
      retries: "{{ web_retries }}"
      delay: "{{ web_delay }}"
      until: neovim_lazy is not failed
      changed_when: neovim_lazy.before != neovim_lazy.after

    - name: Create config directory for lazy
      ansible.builtin.file:
        path: "{{ neovim_base }}_4"
        state: directory
        mode: "0o755"

    - name: Create symlink to LazyVim config
      ansible.builtin.file:
        src: "{{ role_host_path }}/files/lazy_exp"
        dest: "{{ neovim_base }}_4/config"
        state: link
        force: true

- name: Simple configuration version management
  block:
    - name: Create global directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0o755"
      loop:
        - "{{ home }}/.cache"
        - "{{ home }}/.config"
        - "{{ home }}/.local/share"

    - name: Create neovim configuration directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0o755"
      loop:
        - "{{ neovim_base }}_{{ neovim_version }}/cache"
        - "{{ neovim_base }}_{{ neovim_version }}/share"

    - name: Create neovim configuration symlinks
      ansible.builtin.file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
      loop:
        - { src: "{{ neovim_base }}_{{ neovim_version }}/cache", dest: "{{ home }}/.cache/nvim" }
        - { src: "{{ neovim_base }}_{{ neovim_version }}/config", dest: "{{ home }}/.config/nvim" }
        - { src: "{{ neovim_base }}_{{ neovim_version }}/share", dest: "{{ home }}/.local/share/nvim" }

- name: Set up bash
  ansible.builtin.lineinfile:
    path: "{{ home }}/.bashrc"
    regexp: "source .*/{{ role_name }}/files"
    line: source {{ role_host_path }}/files/bash.sh

- name: Create symlink to fish config of {{ role_name }}
  ansible.builtin.file:
    src: "{{ role_host_path }}/files/{{ role_name }}.fish"
    dest: "{{ home }}/.config/fish/conf.d/{{ role_name }}.fish"
    state: link

- name: Create symlinks to fish functions
  ansible.builtin.file:
    src: "{{ role_host_path }}/files/fish_functions/{{ item | basename }}"
    dest: "{{ home }}/.config/fish/functions/{{ item | basename }}"
    state: link
  loop: "{{ lookup('fileglob', '{{ role_path }}/files/fish_functions/*', wantlist=True) }}"
