- name: Install openvpn
  become: true
  ansible.builtin.apt:
    name:
      - openvpn

# sudo openvpn --config /home/rudenkornk/projects/dotfiles/roles/secrets/files/vpn/ee-tll.prod.surfshark.comsurfshark_openvpn_udp.ovpn --auth-user-pass /home/rudenkornk/projects/dotfiles/roles/secrets/files/vpn/surfshark.auth
# sudo nmcli c import type openvpn file /home/rudenkornk/projects/dotfiles/roles/secrets/files/vpn/nikita.rudenko-sc.ovpn
