- name: Create ~/.local/share/fonts directory
  ansible.builtin.file:
    dest: "{{ home }}/.local/share/fonts"
    state: directory
    mode: "0o755"

- name: Download fonts
  ansible.builtin.unarchive:
    src: "{{ manifest[item].url }}"
    dest: "{{ home }}/.local/share/fonts/"
    remote_src: true
  changed_when: false # readme files overwrite each other
  loop:
    - jetbrains_mono
    - fantasque

  retries: "{{ web_retries }}"
  delay: "{{ web_delay }}"
  register: fonts_downloaded
  until: fonts_downloaded is not failed

- name: Install fontconfig
  become: true
  ansible.builtin.package:
    name: fontconfig

- name: Update fonts cache
  ansible.builtin.command: fc-cache --force --verbose
  changed_when: false
